/**
 * Minimal `.env` reader/writer for the spike.
 *
 * Deliberately dependency-free. Generated private keys land here and nowhere
 * else: `.env*` is gitignored (except `.env.example`), and no code path in this
 * repo prints a key value.
 *
 * Two layers, and the difference is load-bearing:
 *   - `.env`       ours. The spike writes generated test keys here.
 *   - `.env.local` the OPERATOR's. May hold real funded mainnet keys. Read
 *                  only, never written, and it WINS on conflicts.
 *
 * That precedence is why `writeEnvValue` verifies its own work: writing
 * `USER1_PRIVATE_KEY` to `.env` while `.env.local` defines the same name
 * produces a file that looks updated and changes nothing, which for a key
 * rotation is the kind of silence that loses funds.
 */
import { chmodSync, readFileSync, writeFileSync, existsSync } from "node:fs";

/** Owner-only file mode for anything holding key material. */
const SECRET_FILE_MODE = 0o600;

/**
 * Which files a call reads and writes. Injectable so tests can exercise the
 * layering against temp files instead of the developer's real secrets.
 */
export type EnvFiles = {
  /** Written by the spike. */
  readonly envPath: URL;
  /** Operator-managed secrets (e.g. USER1_PRIVATE_KEY). Read-only for us. */
  readonly envLocalPath: URL;
};

export const DEFAULT_ENV_FILES: EnvFiles = {
  envPath: new URL("../../.env", import.meta.url),
  envLocalPath: new URL("../../.env.local", import.meta.url),
};

/**
 * Env var naming the ONE key a run is allowed to overwrite.
 *
 * Overwriting a key that already has a value orphans whatever funds sit at the
 * old address, so it takes a deliberate `SPIKE_ROTATE_KEY=<VAR>` rather than a
 * silent upsert.
 */
const ROTATE_VAR = "SPIKE_ROTATE_KEY";

function parseInto(out: Map<string, string>, path: URL): void {
  if (!existsSync(path)) return;
  for (const line of readFileSync(path, "utf8").split(/\r?\n/)) {
    const trimmed = line.trim();
    if (trimmed.length === 0 || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq <= 0) continue;
    const key = trimmed.slice(0, eq).trim();
    const value = trimmed.slice(eq + 1).trim();
    out.set(key, value.replace(/^["']|["']$/g, ""));
  }
}

/**
 * Parse `.env` and `.env.local` into a map; `.env.local` wins on conflicts.
 * Writes only ever go to `.env` — `.env.local` belongs to the operator.
 */
export function readEnvFile(files: EnvFiles = DEFAULT_ENV_FILES): Map<string, string> {
  const out = new Map<string, string>();
  parseInto(out, files.envPath);
  parseInto(out, files.envLocalPath);
  return out;
}

/**
 * Read a value, preferring a real environment variable over the `.env` files so
 * an operator can override without editing anything.
 */
export function readEnvValue(
  key: string,
  files: EnvFiles = DEFAULT_ENV_FILES,
): string | undefined {
  const fromProcess = process.env[key];
  if (fromProcess !== undefined && fromProcess.length > 0) return fromProcess;
  return readEnvFile(files).get(key);
}

/** `true` for `KEY=`, `  KEY =`; `false` for `# KEY=` and for other keys. */
function isAssignmentFor(line: string, key: string): boolean {
  const trimmed = line.trim();
  if (trimmed.startsWith("#")) return false;
  const eq = trimmed.indexOf("=");
  if (eq <= 0) return false;
  return trimmed.slice(0, eq).trim() === key;
}

/**
 * Upsert a key in `.env`, preserving other entries and any header comment.
 *
 * Refuses to clobber an existing non-empty value unless the caller has set
 * `SPIKE_ROTATE_KEY=<key>`, and verifies afterwards that the value it wrote is
 * the value a reader will actually get.
 */
export function writeEnvValue(
  key: string,
  value: string,
  files: EnvFiles = DEFAULT_ENV_FILES,
): void {
  const current = readEnvValue(key, files);
  if (current !== undefined && current.length > 0 && current !== value) {
    if (process.env[ROTATE_VAR] !== key) {
      throw new Error(
        `${key} already has a value; refusing to overwrite it. Anything held at the current address would become unreachable. Set ${ROTATE_VAR}=${key} to rotate deliberately.`,
      );
    }
  }

  const existing = existsSync(files.envPath)
    ? readFileSync(files.envPath, "utf8").split(/\r?\n/)
    : ["# Generated by `npm run spike`. Never commit this file."];

  let replaced = false;
  const next = existing.map((line) => {
    // Commented-out lines are documentation, not assignments: rewriting one
    // would resurrect it, and skipping it without appending would drop the
    // write on the floor.
    if (!isAssignmentFor(line, key)) return line;
    replaced = true;
    return `${key}=${value}`;
  });

  if (!replaced) next.push(`${key}=${value}`);

  writeFileSync(files.envPath, `${next.join("\n").replace(/\n+$/, "")}\n`, {
    encoding: "utf8",
    mode: SECRET_FILE_MODE,
  });
  // `mode` on writeFileSync only applies when the file is created, so an
  // already-loose `.env` stays loose without this.
  try {
    chmodSync(files.envPath, SECRET_FILE_MODE);
  } catch {
    // Windows maps chmod onto the read-only attribute only; a failure here
    // says nothing about whether the write succeeded.
  }

  const effective = readEnvValue(key, files);
  if (effective !== value) {
    throw new Error(
      `${key} was written to .env but reads back differently — a higher-precedence source (process env or .env.local) is shadowing it. The write had no effect.`,
    );
  }
}
