/**
 * `live-lending` — the operator CLI for the Venus "guard on behalf"
 * (MARKETPLACE-LENDING-AGENT §12 / R2.25).
 *
 * It exists so the phase's LIVE GATES can be driven by a person rather than
 * described in a document. Wallet B holds a reserve (BNB partly swapped to USDT
 * and supplied to vUSDT) and calls `repayBorrowBehalf(A, …)` when account A's
 * health factor breaches. Every gate below moves real BNB on chain 56.
 *
 * ─── SUBCOMMANDS ──────────────────────────────────────────────────────────
 *
 *   census      READ-ONLY. Live gate 1. Re-probe every granted and refused
 *               selector in DEPLOYED bytecode, the Venus routing census against
 *               `VENUS_RECORDED_ROUTING`, `vUSDT.underlying()` and the pinned
 *               WBNB/USDT pool. One PASS/FAIL row per fact; a FAIL row is the
 *               grant refusal you would otherwise meet at S1.
 *   guardable   READ-ONLY. The guardable preview for account A: BOTH health
 *               factor bases with their protocol match flags, the markets, which
 *               debts this guard can actually repay, and — with a budget — the
 *               `reserveCapFloorWei` / `minimumCapDayWei` the hire must clear.
 *   preview     READ-ONLY. `checkLendingSizing` run locally, with the reserve
 *               split, the mint estimate, both cap floors AND
 *               `lendingExposureProduct` (cap × 7 days) printed BEFORE a grant
 *               exists — the FINDINGS (r) rule: the product, never the rate.
 *   provision   SPENDS. Live gate 2. Preview → the real S1 hire route → the
 *               on-chain grant with the owner key → convergence, with the grant
 *               cost MEASURED from B's balance either side.
 *   arm         SPENDS. Live gate 3. The owner-signed `lendingArm`: one batch
 *               that swaps the supply leg to USDT and mints vUSDT.
 *   status      READ-ONLY. The guard row and the worker's recorded view, PLUS a
 *               live reserve and account read, each labelled for which it is.
 *   settings    SPENDS (gas-free, but it changes what the worker does with
 *               money). Owner-signed `lendingSettings`, MERGED over the stored
 *               row — a flag changes only the field it names.
 *   retire      SPENDS. Live gate 7. Owner-signed `lendingRetire`, and it
 *               prints the outcome block honestly: HTTP 200 is NOT "retired".
 *   worker      One worker cycle. `--dry-run` IS THE DEFAULT here; a live cycle
 *               takes `--yes-live`. It drives `runLendingWorkerOnce` — the same
 *               entry `scripts/lending-worker.ts` runs — so every in-cycle gate
 *               stays in force.
 *
 * ─── THE SAFETY POSTURE, COPIED FROM `live-grid` / `live-venus` ───────────
 *
 * Every subcommand that can submit anything REFUSES without `--yes-live`, and
 * the refusal carries the figures it would have spent. A missing flag is never
 * a prompt. Unknown flags refuse the run before anything is constructed
 * (`scripts/lending-worker.ts`'s rule: a misspelled `--dry-run` silently
 * ignored would spend where the operator meant to rehearse).
 *
 * KEYS: the owner key is read through `readEnvValue` (process env, then `.env` /
 * `.env.local`, read-only), used to sign, and NEVER logged or persisted. This
 * file contains no key and generates none — the session key is generated by the
 * S1 route inside the plane and sealed by the store.
 *
 * BOOT GATES: `LENDING_ENABLED` (which itself requires `LP_ENABLED` and
 * `HIRE_ENABLED`), chain 56, and — for every command that touches the guard row
 * — `DATABASE_URL`. Each refusal quotes the boot rule it is enforcing rather
 * than guessing at a remedy.
 */
import { randomUUID } from "node:crypto";
import { resolve } from "node:path";
import { pathToFileURL } from "node:url";
import {
  createPublicClient,
  formatEther,
  formatUnits,
  getAddress,
  http,
  isAddress,
  keccak256,
  parseEther,
  parseUnits,
  stringToBytes,
  toFunctionSelector,
  type Address,
  type Hex,
} from "viem";
import { privateKeyToAccount } from "viem/accounts";
import { BNB, BNB_TESTNET, type NetworkConfig } from "@altananetwork/sdk";

import { createServer, type ServerConfig } from "../src/server.js";
import { createAgentStore } from "../src/store/agents.js";
import { createJournal, reconcile } from "../src/store/journal.js";
import { createNonceStore } from "../src/store/nonces.js";
import { createKillSwitch } from "../src/killswitch/killswitch.js";
import { createProviderRegistry } from "../src/wallet/registry.js";
import { AltanaProvider, authorityFromPrivateKey } from "../src/wallet/altana.js";
import { HttpDataPlaneClient } from "../src/clients/dataPlane.js";
import { createKeyStoreReader } from "../src/account/keyStoreReader.js";
import { createGrantEvidenceReader } from "../src/wallet/grantEvidence.js";
import { buildLpServerDeps, type BuiltLpServerDeps } from "../src/lp/wiring.js";
import { resolveLpAddresses, resolveLpRpcUrls } from "../src/lp/readers.js";
import { resolveLpRailConfig } from "../src/lp/rails.js";
import {
  resolveHireGrantGasHeadroomWei,
  resolveLendingEnabled,
  resolveLendingRpcUrls,
  resolveLendingRuntimeConfig,
  resolveTradeConfig,
  VENUS_CORE_COMPTROLLER_56,
} from "../src/ops/config.js";
import {
  buildLendingServerDeps,
  closeLendingServerDeps,
  type BuiltLendingServerDeps,
} from "../src/lending/wiring.js";
import {
  LendingAccountTooComplexError,
  createLendingChainReaders,
  type LendingChainReaders,
  type LendingVenue,
} from "../src/lending/readers.js";
import {
  lendingCapacity,
  lendingTier,
  planLendingRetire,
} from "../src/lending/sizing.js";
import {
  runLendingWorkerOnce,
  type LendingWorkerAgentOutcome,
  type LendingWorkerDeps,
} from "../src/lending/worker.js";
import type { LendingGuardRecord, LendingGuardStore } from "../src/store/lendingGuards.js";
import {
  DEFAULT_LENDING_SETTINGS,
  LENDING_MIN_SECONDS_BETWEEN_ACTIONS,
  lendingSettingsDigest,
  parseLendingSettingsParams,
  type LendingSettings,
} from "../src/http/lendingWire.js";
import {
  LENDING_GRANTED_SELECTORS,
  LENDING_REFUSED_SELECTORS,
  LENDING_RESERVE_BPS_DEFAULT,
  LENDING_RESERVE_BPS_MAX,
  LENDING_RESERVE_BPS_MIN,
  LENDING_VBNB_GRANTED_SELECTORS,
  LENDING_VUSDT_GRANTED_SELECTORS,
  MAX_VENUS_SESSION_SECONDS,
  VENUS_CENSUS_BLOCK,
  VENUS_RECORDED_ROUTING,
  checkLendingSizing,
  lendingExposureProduct,
  lendingHireSizingPreview,
} from "../src/ops/policy.js";
import type { TradeEnv } from "../src/ops/config.js";
import { createVenusChainReaders } from "../src/venus/readers.js";
import { venusBasisView } from "../src/venus/triggers.js";
import type { VenusRoutingCensus } from "../src/ops/policy.js";
import type { VenusVenue } from "../src/venus/types.js";
import { paramsHash } from "../src/auth/canonical.js";
import {
  OWNER_ACTION_TYPES,
  buildOwnerActionDomain,
  resolveDomainSalt,
  type OwnerActionStruct,
  type OwnerActionType,
} from "../src/auth/ownerAuth.js";
import { sanitizeMessage } from "../src/core/errors.js";
import { readEnvValue } from "./spike/env.js";

/* -------------------------------------------------------------------------- */
/* Commands, flags and gates — PURE, and exported for `test/lending.cli.test.ts` */
/* -------------------------------------------------------------------------- */

export const LENDING_CLI_COMMANDS = [
  "census",
  "guardable",
  "preview",
  "provision",
  "arm",
  "status",
  "settings",
  "retire",
  "worker",
] as const;

export type LendingCliCommand = (typeof LENDING_CLI_COMMANDS)[number];

/**
 * Subcommands that can SUBMIT something, consume a nonce, or change what the
 * worker will later do with money.
 *
 * `settings` is here for the `live-grid` reason: it costs no gas, but it is the
 * object the worker recomputes its digest against every cycle, so signing it is
 * a decision about money even though the signature itself is free.
 *
 * `worker` is here CONDITIONALLY — see {@link commandIsLive}: its default is a
 * rehearsal, so it is only a spending path once `--yes-live` asks for one, and
 * that is exactly the flag the gate looks for.
 */
export const LENDING_CLI_LIVE_COMMANDS: ReadonlySet<LendingCliCommand> = new Set([
  "provision",
  "arm",
  "settings",
  "retire",
  "worker",
]);

/**
 * The read-only chain probes: no store, no HTTP route, and — the point —
 * **no enablement**.
 *
 * They all reach the chain through `readOnlyLending()`, which resolves config
 * and builds a public client. None of them drives a `/lending/*` route, so the
 * "a run here would report 404s" reasoning behind the `LENDING_ENABLED` gate is
 * simply false for these three.
 *
 * It also made the runbook's own gate 1 unrunnable in the state it is written
 * for. `census` exists so a moved routing census or an unset
 * `VENUS_PRIME_ADDRESS` is found BEFORE the flag is flipped — a gate that
 * demands the flag first cannot do that job. Same for gate 2's `preview`, which
 * prints the exposure product the operator is supposed to read before granting
 * anything.
 *
 * They still get every other gate: a malformed flag is still a boot error, and
 * chain 56 is still required, because a census taken anywhere else means
 * nothing.
 */
export const LENDING_CLI_STORELESS_COMMANDS: ReadonlySet<LendingCliCommand> = new Set([
  "census",
  "guardable",
  "preview",
]);

const COMMON_FLAGS = ["yes-live"] as const;

/**
 * The CLOSED flag set per subcommand. Anything outside it refuses the run.
 *
 * This is not tidiness. `--dry-run` on `worker` inverts a spending decision and
 * `--yes-live` unlocks one; a typo in either that the parser shrugged at would
 * spend where the operator meant to rehearse, or would leave the operator
 * believing a rehearsal was live.
 */
export const LENDING_CLI_KNOWN_FLAGS: Readonly<
  Record<LendingCliCommand, readonly string[]>
> = {
  census: [...COMMON_FLAGS, "rpc-url"],
  guardable: [...COMMON_FLAGS, "account", "budget", "reserve-pct", "rescues", "max-repay-usdt"],
  preview: [
    ...COMMON_FLAGS,
    "account",
    "budget",
    "reserve-pct",
    "rescues",
    "max-repay-usdt",
    "cap-day",
    "reserve-cap",
    "mint-usdt",
    "tier-buyback-usdt",
    "ttl-sec",
  ],
  provision: [
    ...COMMON_FLAGS,
    "agent-id",
    "account",
    "wallet",
    "budget",
    "reserve-pct",
    "rescues",
    "max-repay-usdt",
    "max-repay-bnb",
    "cap-day",
    "reserve-cap",
    "markets",
    "trigger-hf",
    "target-hf",
    "notify-below-hf",
    "min-seconds",
    "ttl-sec",
  ],
  arm: [...COMMON_FLAGS, "agent-id"],
  status: [...COMMON_FLAGS, "agent-id"],
  settings: [
    ...COMMON_FLAGS,
    "agent-id",
    "trigger-hf",
    "target-hf",
    "notify-below-hf",
    "clear-notify-below-hf",
    "min-seconds",
    "rescues",
    "max-repay-usdt",
    "max-repay-bnb",
  ],
  retire: [...COMMON_FLAGS, "agent-id", "accept-partial"],
  worker: [...COMMON_FLAGS, "agent-id", "once", "dry-run"],
};

export type Flags = ReadonlyMap<string, string>;

/** `--a b`, `--a=b` and bare `--a` (which becomes `"true"`). */
export function parseFlags(argv: readonly string[]): Flags {
  const map = new Map<string, string>();
  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];
    if (arg === undefined || !arg.startsWith("--")) continue;
    const eq = arg.indexOf("=");
    if (eq > 0) {
      map.set(arg.slice(2, eq), arg.slice(eq + 1));
      continue;
    }
    const next = argv[i + 1];
    if (next !== undefined && !next.startsWith("--")) {
      map.set(arg.slice(2), next);
      i += 1;
    } else {
      map.set(arg.slice(2), "true");
    }
  }
  return map;
}

/** Every flag name the command does not know. Sorted, for a stable message. */
export function unknownFlags(
  command: LendingCliCommand,
  flags: Flags,
): readonly string[] {
  const known = new Set(LENDING_CLI_KNOWN_FLAGS[command]);
  return [...flags.keys()].filter((name) => !known.has(name)).sort();
}

export function assertKnownFlags(command: LendingCliCommand, flags: Flags): void {
  const unknown = unknownFlags(command, flags);
  if (unknown.length === 0) return;
  throw new Error(
    `Unknown flag(s) for \`${command}\`: ${unknown.map((name) => `--${name}`).join(", ")}. `
      + `Known: ${LENDING_CLI_KNOWN_FLAGS[command].map((name) => `--${name}`).join(", ")}. `
      + "Refusing to run — a misspelled flag on this CLI is one keystroke from spending, "
      + "so it is never silently ignored.",
  );
}

export function isYesLive(flags: Flags): boolean {
  return flags.get("yes-live") === "true";
}

/**
 * Whether THIS invocation can submit. `worker` rehearses unless asked not to.
 */
export function commandIsLive(command: LendingCliCommand, flags: Flags): boolean {
  if (!LENDING_CLI_LIVE_COMMANDS.has(command)) return false;
  if (command === "worker") return isYesLive(flags) && flags.get("dry-run") !== "true";
  return true;
}

/**
 * THE GATE, as a pure function: the refusal text, or `null` to proceed.
 *
 * `requireYesLive` is only the printing half. Keeping the decision here means
 * the offline suite tests the SAME predicate the CLI runs rather than a
 * paraphrase of it.
 */
export function yesLiveGate(input: {
  readonly command: LendingCliCommand;
  readonly flags: Flags;
  readonly chainId: number;
  readonly networkLabel: string;
  readonly wouldSpend: string;
}): string | null {
  if (!commandIsLive(input.command, input.flags)) return null;
  if (isYesLive(input.flags)) return null;
  return yesLiveRefusal(
    input.command, input.chainId, input.networkLabel, input.wouldSpend,
  );
}

/** The refusal text, so the test can assert it names the figures and the flag. */
export function yesLiveRefusal(
  command: LendingCliCommand,
  chainId: number,
  networkLabel: string,
  wouldSpend: string,
): string {
  return (
    `\nREFUSED: \`${command}\` acts for real on chain ${chainId} (${networkLabel}).\n`
    + `It would: ${wouldSpend}\n`
    + "Re-run with --yes-live if that is what you want. Nothing was sent."
  );
}

/**
 * The boot gates, as a PURE check that returns the refusal or `null`.
 *
 * Each message quotes the rule it enforces — `src/ops/config.ts`'s resolver for
 * the flag triple, `src/lending/wiring.ts` for `DATABASE_URL` and chain 56 —
 * because "lending is off" is a fact about the deployment and an operator who
 * is told which line refused can fix it in one step.
 */
export function checkBootGates(input: {
  /**
   * `TradeEnv`, not `NodeJS.ProcessEnv`, so an offline test can hand this a
   * plain record. `process.env` is assignable to it.
   */
  readonly env: TradeEnv;
  readonly chainId: number;
  readonly command: LendingCliCommand;
}): string | null {
  let enabled: boolean;
  try {
    enabled = resolveLendingEnabled(input.env);
  } catch (error) {
    // `resolveLendingEnabled` is also the ONE place `LP_ENABLED` and
    // `HIRE_ENABLED` are required (src/lending/wiring.ts's docstring), so its
    // own text is the most precise thing that can be said here.
    return error instanceof Error ? error.message : "LENDING_ENABLED is malformed.";
  }
  // The read-only probes run with the guard OFF, deliberately: they are how an
  // operator checks a deployment BEFORE enabling it (runbook gates 1 and 2).
  if (!enabled && !LENDING_CLI_STORELESS_COMMANDS.has(input.command)) {
    return (
      'LENDING_ENABLED is not "true". `live-lending` refuses on a deployment that has not '
      + "enabled the guard: every route it drives is registered only when `deps.lending` is "
      + "wired, so a run here would report 404s that mean \"off\", not \"broken\". "
      + "`census`, `preview` and `guardable` read the chain directly and DO run with the "
      + "guard off — check the deployment with those first."
    );
  }
  if (input.chainId !== 56) {
    return (
      `The lending guard is chain-56 only; this run resolves chain ${input.chainId}. `
      + "The selector census was taken on BNB mainnet and means nothing anywhere else "
      + "(src/lending/wiring.ts)."
    );
  }
  if (LENDING_CLI_STORELESS_COMMANDS.has(input.command)) return null;
  if ((input.env["DATABASE_URL"] ?? "").trim() === "") {
    return (
      "DATABASE_URL is unset. The lending guard row IS the worker's queue and the arm's "
      + "idle gate: a memory store here would accept an owner-signed arm the worker can "
      + "never see, and would evaporate on restart (src/lending/wiring.ts)."
    );
  }
  return null;
}

/* -------------------------------------------------------------------------- */
/* The sizing report — PURE, and the reason `preview` exists                  */
/* -------------------------------------------------------------------------- */

export type LendingPreviewInput = {
  readonly budgetWei: bigint;
  readonly reserveBps: number;
  readonly rescueReserveCount: number;
  readonly mintUsdtWei: bigint;
  readonly tierBuyBackUsdtWei: bigint;
  /** The caps the operator intends to grant. `null` ⇒ price at the floor. */
  readonly capDayWei: bigint | null;
  readonly reserveCapWei: bigint | null;
  readonly usdt: Address;
  readonly ttlSec: number;
};

/**
 * Everything `preview` prints, derived once so the CLI cannot show one figure
 * and grant another.
 *
 * The exposure product is NOT optional and NOT a footnote (FINDINGS (r),
 * restated by R3.2 and by `provision-venus-agent`): Altana caps are rolling per
 * period with no lifetime ceiling, so a 0.05 BNB/day cap under the 7-day
 * session ceiling is 0.35 BNB of authority. The rate on its own is the number
 * that hid that.
 */
export function lendingPreviewReport(
  input: LendingPreviewInput,
): readonly string[] {
  const preview = lendingHireSizingPreview({
    budgetWei: input.budgetWei,
    reserveBps: input.reserveBps,
    capDayWei: input.capDayWei ?? 0n,
    reserveCapWei: input.reserveCapWei ?? 0n,
    mintUsdtWei: input.mintUsdtWei,
    tierBuyBackUsdtWei: input.tierBuyBackUsdtWei,
    rescueReserveCount: input.rescueReserveCount,
  });
  const capDayWei = input.capDayWei ?? BigInt(preview.minimumCapDayWei);
  const reserveCapWei = input.reserveCapWei ?? BigInt(preview.reserveCapFloorWei);
  const sized = checkLendingSizing({
    budgetWei: input.budgetWei,
    reserveBps: input.reserveBps,
    capDayWei,
    reserveCapWei,
    mintUsdtWei: input.mintUsdtWei,
    tierBuyBackUsdtWei: input.tierBuyBackUsdtWei,
    rescueReserveCount: input.rescueReserveCount,
  });
  const exposure = lendingExposureProduct({
    nativeDailyCapWei: capDayWei,
    usdt: input.usdt,
    usdtDailyCapWei: reserveCapWei,
    sessionSeconds: input.ttlSec,
  });
  const lines: string[] = [
    `budget            : ${formatEther(input.budgetWei)} BNB`,
    `reserve split     : ${input.reserveBps} bps ⇒ BNB tier ${formatEther(BigInt(preview.reserveNativeWei))}`
      + ` / supply leg ${formatEther(BigInt(preview.supplyNativeWei))} BNB`,
    `mint estimate     : ${formatUnits(input.mintUsdtWei, 18)} USDT (the arm's minOut, floored)`,
    `tier buy-back     : ${formatUnits(input.tierBuyBackUsdtWei, 18)} USDT (what the BNB tier could re-buy)`,
    `usdt reserve ceil : ${formatUnits(BigInt(preview.usdtReserveCeilingWei), 18)} USDT`,
    `USDT cap floor    : ${formatUnits(BigInt(preview.reserveCapFloorWei), 18)} USDT`
      + `   (reserveCapWei must be at least this)`,
    `native cap floor  : ${formatEther(BigInt(preview.minimumCapDayWei))} BNB`
      + `   (capDayWei must be at least this)`,
    `tier floor        : ${formatEther(BigInt(preview.tierFloorWei))} BNB`
      + ` = wallet floor + ${preview.rescueReserveCount} × relay fee`,
    `relay fee/submit  : ${formatEther(BigInt(preview.relayFeePerSubmitWei))} BNB`
      + "   (RELAY_FEE_PER_EXIT_WEI — still a PAD, not a measurement)",
    `caps priced       : native ${formatEther(capDayWei)} BNB/day, `
      + `USDT ${formatUnits(reserveCapWei, 18)}/day`
      + `${input.capDayWei === null || input.reserveCapWei === null ? "  (priced AT THE FLOOR — you named no cap)" : ""}`,
    `sizing            : ${sized.ok ? "ok" : `REFUSED — ${sized.message}`}`,
  ];
  lines.push(
    "",
    "EXPOSURE PRODUCT (FINDINGS (r): the product, never the rate) —",
    `  session          : ${exposure.periods} rolling day(s), TTL ${input.ttlSec}s`
      + ` (ceiling ${MAX_VENUS_SESSION_SECONDS}s)`,
    `  native           : ${formatEther(capDayWei)} BNB/day × ${exposure.periods}`
      + ` = ${formatEther(exposure.nativeProductWei)} BNB over this session`,
  );
  for (const entry of exposure.tokenProducts) {
    lines.push(
      `  ${entry.token} : × ${exposure.periods} = ${formatUnits(entry.productWei, 18)} USDT`,
    );
  }
  lines.push(
    "  A leaked session key reaches `approve` on USDT with an UNCONSTRAINED SPENDER and the",
    "  granted router with an UNCONSTRAINED RECIPIENT, bounded ONLY by those caps per rolling",
    "  day and by the expiry. The cap is a BUDGET, not a gate (lendingSessionSpec, R2.2).",
    "",
    "  THIS CHECK IS AN EARLY WARNING, NOT A GUARANTEE: it reserves per-submission arithmetic",
    "  on RELAY_FEE_PER_EXIT_WEI, and a rescue is NEVER refused for want of headroom.",
  );
  return lines;
}

/* -------------------------------------------------------------------------- */
/* The census — PURE comparison over facts a caller read                      */
/* -------------------------------------------------------------------------- */

export type CensusRow = {
  readonly name: string;
  readonly expected: string;
  readonly observed: string;
  readonly pass: boolean;
};

export type CensusObservation = {
  readonly blockNumber: bigint;
  /** Selector presence in DEPLOYED bytecode, keyed `"<target>:<signature>"`. */
  readonly selectorsPresent: ReadonlyMap<string, boolean>;
  readonly vUsdt: Address;
  readonly vBnb: Address;
  readonly usdtFromUnderlying: Address;
  readonly usdtFromBoot: Address;
  readonly routing: VenusRoutingCensus;
  readonly pool: { readonly address: Address; readonly liquidity: bigint; readonly token0: Address };
};

const sameAddress = (left: string, right: string): boolean =>
  left.toLowerCase() === right.toLowerCase();

/**
 * Turn one probe into PASS/FAIL rows.
 *
 * The GRANTED selectors must be PRESENT (a grant that names a selector the
 * bytecode does not carry is a rule that can never fire, and — worse — a rule
 * the operator believes bounds something). The REFUSED list is NOT asserted
 * absent: `redeem(uint256)` and `borrow(uint256)` are present in vUSDT and
 * always will be — what matters is that `lendingSessionSpec` never grants them,
 * which is a template property the offline suite pins, not a chain fact.
 * Printing them here keeps the two lists visible side by side.
 */
export function censusRows(observed: CensusObservation): readonly CensusRow[] {
  const rows: CensusRow[] = [];
  const selector = (target: Address, signature: string): void => {
    const key = `${target.toLowerCase()}:${signature}`;
    const present = observed.selectorsPresent.get(key) ?? false;
    rows.push({
      name: `granted ${signature} @ ${target}`,
      expected: `present (${toFunctionSelector(signature)})`,
      observed: present ? "present" : "ABSENT",
      pass: present,
    });
  };
  for (const signature of LENDING_VUSDT_GRANTED_SELECTORS) {
    selector(observed.vUsdt, signature);
  }
  for (const signature of LENDING_VBNB_GRANTED_SELECTORS) {
    selector(observed.vBnb, signature);
  }
  rows.push({
    name: "vUSDT.underlying() equals the boot-derived USDT",
    expected: observed.usdtFromBoot,
    observed: observed.usdtFromUnderlying,
    pass: sameAddress(observed.usdtFromBoot, observed.usdtFromUnderlying),
  });
  rows.push({
    name: `routing: claimVenus facet (census block ${VENUS_CENSUS_BLOCK})`,
    expected: VENUS_RECORDED_ROUTING.claimVenusFacet,
    observed: observed.routing.claimVenusFacet,
    pass: sameAddress(VENUS_RECORDED_ROUTING.claimVenusFacet, observed.routing.claimVenusFacet),
  });
  rows.push({
    name: "routing: Prime implementation",
    expected: VENUS_RECORDED_ROUTING.primeImplementation,
    observed: observed.routing.primeImplementation,
    pass: sameAddress(
      VENUS_RECORDED_ROUTING.primeImplementation,
      observed.routing.primeImplementation,
    ),
  });
  for (const [vToken, implementation] of observed.routing.vTokenImplementations) {
    rows.push({
      name: `routing: ${vToken} implementation`,
      expected: VENUS_RECORDED_ROUTING.vBep20Implementation,
      observed: implementation,
      pass: sameAddress(VENUS_RECORDED_ROUTING.vBep20Implementation, implementation),
    });
  }
  rows.push({
    name: "pinned WBNB/USDT pool carries liquidity",
    expected: "> 0",
    observed: `${observed.pool.liquidity} @ ${observed.pool.address} (token0 ${observed.pool.token0})`,
    pass: observed.pool.liquidity > 0n,
  });
  return rows;
}

/* -------------------------------------------------------------------------- */
/* Impure: network, keys, flag readers                                        */
/* -------------------------------------------------------------------------- */

const IS_MAINNET = (process.env["EXECUTION_NETWORK"] ?? "").trim() === "mainnet";
const NETWORK: NetworkConfig = IS_MAINNET ? BNB : BNB_TESTNET;
const NETWORK_LABEL = IS_MAINNET ? "mainnet" : "testnet";
const KEY_STORE = getAddress(NETWORK.keyStore);
const READER_NETWORK = {
  chain: NETWORK.chain,
  chainId: NETWORK.chainId,
  publicRpcUrl: NETWORK.publicRpcUrl,
};

function need(flags: Flags, name: string): string {
  const value = flags.get(name);
  if (value === undefined || value.trim() === "" || value === "true") {
    throw new Error(`--${name} is required.`);
  }
  return value.trim();
}

function needAddress(flags: Flags, name: string): Address {
  const raw = need(flags, name);
  if (!isAddress(raw, { strict: false })) {
    throw new Error(`--${name} is not a valid address.`);
  }
  return getAddress(raw);
}

function optionalAddress(flags: Flags, name: string): Address | undefined {
  const raw = flags.get(name);
  if (raw === undefined || raw === "true" || raw.trim() === "") return undefined;
  if (!isAddress(raw.trim(), { strict: false })) {
    throw new Error(`--${name} is not a valid address.`);
  }
  return getAddress(raw.trim());
}

function intFlag(flags: Flags, name: string, fallback: number): number {
  const raw = flags.get(name);
  if (raw === undefined || raw === "true") return fallback;
  const parsed = Number(raw);
  if (!Number.isInteger(parsed)) throw new Error(`--${name} must be an integer.`);
  return parsed;
}

function etherFlag(flags: Flags, name: string): bigint | undefined {
  const raw = flags.get(name);
  if (raw === undefined || raw === "true" || raw.trim() === "") return undefined;
  return parseEther(raw.trim());
}

function usdtFlag(flags: Flags, name: string): bigint | undefined {
  const raw = flags.get(name);
  if (raw === undefined || raw === "true" || raw.trim() === "") return undefined;
  // BSC-USDT carries 18 decimals, which is why every USDT figure in this phase
  // is an 18-decimal wei string and never a 6-decimal one.
  return parseUnits(raw.trim(), 18);
}

function mantissaFlag(flags: Flags, name: string): bigint | undefined {
  const raw = flags.get(name);
  if (raw === undefined || raw === "true" || raw.trim() === "") return undefined;
  return parseUnits(raw.trim(), 18);
}

/** `--reserve-pct 20` ⇒ 2000 bps. Bounded exactly where the policy bounds it. */
function reserveBpsFlag(flags: Flags): number {
  const raw = flags.get("reserve-pct");
  if (raw === undefined || raw === "true") return LENDING_RESERVE_BPS_DEFAULT;
  const pct = Number(raw);
  if (!Number.isFinite(pct)) throw new Error("--reserve-pct must be a percentage, e.g. 20.");
  const bps = Math.round(pct * 100);
  if (bps < LENDING_RESERVE_BPS_MIN || bps > LENDING_RESERVE_BPS_MAX) {
    throw new Error(
      `--reserve-pct must be between ${LENDING_RESERVE_BPS_MIN / 100} and `
        + `${LENDING_RESERVE_BPS_MAX / 100} (percent of the budget kept as BNB).`,
    );
  }
  return bps;
}

function ownerKey(): Hex {
  const varName =
    readEnvValue("SPIKE_OWNER_KEY_VAR")
    ?? (IS_MAINNET ? "USER1_PRIVATE_KEY" : "OWNER_TEST_KEY");
  const value = readEnvValue(varName);
  if (value === undefined || value.trim() === "") {
    throw new Error(
      `No owner key: ${varName} is unset. Put it in .env.local; this script never generates one.`,
    );
  }
  return value.trim() as Hex;
}

function requireYesLive(
  command: LendingCliCommand,
  flags: Flags,
  wouldSpend: string,
): void {
  const refusal = yesLiveGate({
    command,
    flags,
    chainId: NETWORK.chainId,
    networkLabel: NETWORK_LABEL,
    wouldSpend,
  });
  if (refusal === null) return;
  console.error(refusal);
  process.exitCode = 1;
  throw new Error(YES_LIVE_SENTINEL);
}

const YES_LIVE_SENTINEL = "--yes-live not supplied";

function requireBoot(command: LendingCliCommand): void {
  const refusal = checkBootGates({
    env: process.env,
    chainId: NETWORK.chainId,
    command,
  });
  if (refusal !== null) throw new Error(refusal);
}

function show(label: string, value: unknown): void {
  console.log(`\n${label}:`);
  console.log(
    JSON.stringify(value, (_key, entry: unknown) =>
      typeof entry === "bigint" ? entry.toString(10) : entry, 2),
  );
}

/* -------------------------------------------------------------------------- */
/* Read-only venue + readers (no store, no DATABASE_URL)                      */
/* -------------------------------------------------------------------------- */

const VTOKEN_UNDERLYING_ABI = [
  {
    type: "function", name: "underlying", stateMutability: "view",
    inputs: [], outputs: [{ type: "address" }],
  },
] as const;

/**
 * The venue `buildLendingServerDeps` resolves, MINUS the stores.
 *
 * It exists because `census`, `guardable` and `preview` write nothing and need
 * no queue, and requiring a reachable Postgres to read a health factor would
 * make the cheapest gates the hardest to run. It performs the SAME two
 * derivations the wiring does — `vUSDT.underlying()` for USDT and the factory
 * read for the pinned pool — and any divergence between the two is a bug: the
 * BOOT remains the authority, and it refuses a deployment this helper would
 * merely report on.
 */
async function readOnlyLending(): Promise<{
  readonly venue: LendingVenue;
  readonly venusVenue: VenusVenue;
  readonly readers: LendingChainReaders;
  readonly rpcUrls: readonly string[];
  readonly maxSagaSlippageBps: number;
}> {
  const runtime = resolveLendingRuntimeConfig(process.env);
  // `resolveLpAddresses` takes the router and WBNB from its OPTIONS, not from
  // the environment — `LP_NFPM`, `LP_V3_FACTORY` and `LP_QUOTER_V2` are the
  // only three it reads itself. Passing neither made it report
  // "VENUE_PANCAKE_ROUTER_V3, VENUE_WBNB missing" no matter what was set, so
  // `census`, `preview` and `guardable` could never run at all. Both correct
  // call sites resolve the venue first and hand it in; this mirrors
  // `scripts/lp-worker.ts:294`.
  const routerV3Raw = (process.env["VENUE_PANCAKE_ROUTER_V3"] ?? "").trim();
  const wbnbRaw = (process.env["VENUE_WBNB"] ?? "").trim();
  const lpAddresses = resolveLpAddresses(process.env, {
    chainId: NETWORK.chainId,
    keyStore: KEY_STORE,
    ...(routerV3Raw === "" ? {} : { routerV3: getAddress(routerV3Raw) }),
    ...(wbnbRaw === "" ? {} : { wbnb: getAddress(wbnbRaw) }),
  });
  const rails = resolveLpRailConfig(process.env);
  if (!rails.ok) {
    throw new Error(
      "The LP manipulation rails are unset, so `maxSagaSlippageBps` — the ONE floor every "
        + `lending swap leg is derived from — has no value (${rails.failure.keys.join(", ")}).`,
    );
  }
  const rpcUrls = resolveLendingRpcUrls(process.env, READER_NETWORK.publicRpcUrl);
  const primeRaw = (process.env["VENUS_PRIME_ADDRESS"] ?? "").trim();
  const venusVenue: VenusVenue = {
    comptroller: VENUS_CORE_COMPTROLLER_56,
    vBnb: runtime.venue.vBnb,
    prime: primeRaw === "" ? VENUS_CORE_COMPTROLLER_56 : getAddress(primeRaw),
    treasury: runtime.venue.treasury,
  };

  const client = createPublicClient({
    chain: READER_NETWORK.chain,
    transport: http(rpcUrls[0] ?? READER_NETWORK.publicRpcUrl),
  });
  const usdt = getAddress(
    await client.readContract({
      address: runtime.venue.vUsdt,
      abi: VTOKEN_UNDERLYING_ABI,
      functionName: "underlying",
    }),
  );

  const base: LendingVenue = {
    vUsdt: runtime.venue.vUsdt,
    usdt,
    vBnb: runtime.venue.vBnb,
    routerV3: getAddress(lpAddresses.routerV3),
    wbnb: getAddress(lpAddresses.wbnb),
    quoterV2: getAddress(lpAddresses.quoterV2),
    factoryV3: getAddress(lpAddresses.factory),
    swapPool: getAddress(lpAddresses.routerV3),
    swapFeeTier: runtime.venue.swapFeeTier,
    treasury: runtime.venue.treasury,
  };
  const probe = createLendingChainReaders({
    network: READER_NETWORK, rpcUrls, venue: base, venusVenue,
  });
  const pool = await probe.readSwapPool();
  const venue: LendingVenue = { ...base, swapPool: pool.pool };
  return {
    venue,
    venusVenue,
    readers: createLendingChainReaders({
      network: READER_NETWORK, rpcUrls, venue, venusVenue,
    }),
    rpcUrls,
    maxSagaSlippageBps: rails.config.maxSagaSlippageBps,
  };
}

/* -------------------------------------------------------------------------- */
/* The in-process stack (the `live-grid` shape)                               */
/* -------------------------------------------------------------------------- */

type Stack = {
  readonly app: ReturnType<typeof createServer>;
  readonly execToken: string;
  readonly agentStore: Awaited<ReturnType<typeof createAgentStore>>;
  readonly journal: Awaited<ReturnType<typeof createJournal>>;
  readonly killswitch: Awaited<ReturnType<typeof createKillSwitch>>;
  readonly provider: AltanaProvider;
  readonly lending: BuiltLendingServerDeps;
  readonly lp: BuiltLpServerDeps;
  /** Present only when the stack was built `withHire`. */
  readonly hireEvidence?: ReturnType<typeof createGrantEvidenceReader>;
  readonly grantGasHeadroomWei?: bigint;
  close(): Promise<void>;
};

async function buildStack(options: { readonly withHire: boolean }): Promise<Stack> {
  const tradeConfig = resolveTradeConfig(process.env, {
    chainId: NETWORK.chainId,
    keyStore: KEY_STORE,
  });
  const rpcUrls = resolveLpRpcUrls(process.env, READER_NETWORK);
  const lp = await buildLpServerDeps({
    env: process.env,
    network: READER_NETWORK,
    rpcUrls,
    keyStore: KEY_STORE,
    venues: tradeConfig.venues,
  });
  const rails = resolveLpRailConfig(process.env);
  if (!rails.ok) {
    throw new Error(
      `The LP manipulation rails are unset (${rails.failure.keys.join(", ")}); a guard whose `
        + "swaps have no slippage floor must not run.",
    );
  }
  const lending = await buildLendingServerDeps({
    env: process.env,
    network: READER_NETWORK,
    lpVenue: {
      routerV3: lp.addresses.routerV3,
      wbnb: lp.addresses.wbnb,
      quoterV2: lp.addresses.quoterV2,
      factoryV3: lp.addresses.factory,
      maxSagaSlippageBps: rails.config.maxSagaSlippageBps,
    },
  });
  if (lending === undefined) {
    throw new Error(
      "The lending deps did not build. `LENDING_ENABLED` resolved false after the boot gate "
        + "passed, which means the environment changed mid-run; refusing rather than guessing.",
    );
  }

  const agentStore = await createAgentStore();
  const journal = await createJournal();
  const nonceStore = await createNonceStore();
  const killswitch = await createKillSwitch();
  const provider = new AltanaProvider({ network: NETWORK, rpcUrls: [...rpcUrls] });
  const providerRegistry = createProviderRegistry([
    { network: NETWORK, options: { rpcUrls } },
  ]);
  const keyStoreReader = createKeyStoreReader({
    network: READER_NETWORK, rpcUrls, keyStore: KEY_STORE,
  });

  const dataPlaneUrl = process.env["DATA_PLANE_URL"]?.trim() ?? "";
  if (dataPlaneUrl === "") {
    throw new Error("DATA_PLANE_URL is required (the server dependency; .env carries it).");
  }
  const dataPlaneToken = process.env["DATA_PLANE_TOKEN"]?.trim() ?? "";

  // The hire deps are composed ONLY for `provision`, and exactly as
  // `src/index-server.ts` composes them — the same evidence reader, the same
  // headroom resolver, the same treasury. A second spelling of the funding
  // requirement would be a second number to keep honest.
  let hire: {
    readonly evidence: ReturnType<typeof createGrantEvidenceReader>;
    readonly nfpm: Address;
    readonly routerV3: Address;
    readonly wbnb: Address;
    readonly treasury: Address;
    readonly feeBps: number;
    readonly relayFeePerSubmitWei: bigint;
    readonly grantGasHeadroomWei: bigint;
  } | undefined;
  const relayFeePerSubmitWei: bigint | undefined = lp.lp.relayFeePerSubmitWei;
  let grantGasHeadroomWei: bigint | undefined;
  if (options.withHire) {
    if (relayFeePerSubmitWei === undefined) {
      throw new Error(
        "The LP wiring resolved no `relayFeePerSubmitWei`, so the hire's grant-gas headroom "
          + "cannot be sized. `HIRE_ENABLED` requires LP wiring (src/index-server.ts).",
      );
    }
    if (tradeConfig.feeTreasury === undefined) {
      throw new Error(
        "FEE_TREASURY_ADDRESS is required for the hire route (HIRE_ENABLED requires BNB "
          + "mainnet, DATABASE_URL, EXECUTION_MASTER_KEY, encrypted durable Postgres, "
          + "passkeys, LP wiring, and FEE_TREASURY_ADDRESS — src/index-server.ts).",
      );
    }
    if (!agentStore.durable || !agentStore.keyEncryptionConfigured) {
      throw new Error(
        "The hire route needs an encrypted, durable Postgres agent store "
          + "(DATABASE_URL + EXECUTION_MASTER_KEY). Refusing rather than sealing a session "
          + "key into a store that evaporates.",
      );
    }
    grantGasHeadroomWei = resolveHireGrantGasHeadroomWei(process.env, relayFeePerSubmitWei);
    hire = {
      evidence: createGrantEvidenceReader({
        network: { ...READER_NETWORK, keyStoreController: getAddress(NETWORK.keyStoreController) },
        rpcUrls,
        keyStoreReader,
      }),
      nfpm: lp.addresses.nfpm,
      routerV3: lp.addresses.routerV3,
      wbnb: lp.addresses.wbnb,
      treasury: tradeConfig.feeTreasury,
      feeBps: tradeConfig.feeBps ?? 0,
      relayFeePerSubmitWei,
      grantGasHeadroomWei,
    };
  }

  const execToken = `live-lending-${randomUUID()}`;
  const envSalt = process.env["EXECUTION_ENV_SALT"]?.trim();
  const config: ServerConfig = {
    chainId: NETWORK.chainId,
    network: NETWORK_LABEL,
    keyStore: KEY_STORE,
    execToken,
    operatorToken: `live-lending-op-${randomUUID()}`,
    trade: tradeConfig,
    ...(envSalt === undefined || envSalt === "" ? {} : { envSalt }),
  };

  const app = createServer({
    agentStore,
    journal,
    nonceStore,
    killswitch,
    providerRegistry,
    dataPlane: new HttpDataPlaneClient({
      baseUrl: dataPlaneUrl,
      ...(dataPlaneToken === "" ? {} : { token: dataPlaneToken }),
    }),
    lp: lp.lp,
    keyStoreReader,
    lending: {
      guards: lending.guards,
      settingsStore: lending.settingsStore,
      observations: lending.observations,
      readers: lending.readers,
      venue: lending.venue,
      intervalMs: lending.intervalMs,
      maxObservationAgeMs: lending.maxObservationAgeMs,
      maxSagaSlippageBps: lending.maxSagaSlippageBps,
      previewSecret: lending.previewSecret,
      ...(lending.routing === undefined ? {} : { routing: lending.routing }),
    },
    ...(hire === undefined ? {} : { hire }),
    config,
  });

  return {
    app,
    execToken,
    agentStore,
    journal,
    killswitch,
    provider,
    lending,
    lp,
    ...(hire === undefined ? {} : { hireEvidence: hire.evidence }),
    ...(grantGasHeadroomWei === undefined ? {} : { grantGasHeadroomWei }),
    async close(): Promise<void> {
      lp.evidence?.observer.stop();
      for (const closeable of [journal, nonceStore, killswitch, agentStore, lp.lp.store, lp.lp.settingsStore]) {
        try {
          await closeable.close();
        } catch {
          /* independent closes */
        }
      }
      await closeLendingServerDeps(lending);
    },
  };
}

/* -------------------------------------------------------------------------- */
/* Owner-action signing and transport                                          */
/* -------------------------------------------------------------------------- */

type SignedEnvelope = {
  readonly signed: Record<string, unknown>;
  readonly signature: Hex;
  readonly params: unknown;
};

async function signOwnerAction(
  action: OwnerActionType,
  agentId: string,
  params: unknown,
): Promise<SignedEnvelope> {
  const account = privateKeyToAccount(ownerKey());
  const nowSec = Math.floor(Date.now() / 1000);
  const envSalt = process.env["EXECUTION_ENV_SALT"]?.trim();
  const message: OwnerActionStruct = {
    owner: account.address,
    agentId,
    action,
    paramsHash: paramsHash(action, params),
    nonce: keccak256(stringToBytes(`live-lending-${randomUUID()}`)),
    issuedAt: BigInt(nowSec - 5),
    expiry: BigInt(nowSec + 120),
  };
  const signature = await account.signTypedData({
    domain: buildOwnerActionDomain(
      NETWORK.chainId,
      resolveDomainSalt({
        chainId: NETWORK.chainId,
        network: NETWORK_LABEL,
        ...(envSalt === undefined || envSalt === "" ? {} : { envSalt }),
      }),
    ),
    types: OWNER_ACTION_TYPES,
    primaryType: "OwnerAction",
    message,
  });
  return {
    signed: {
      owner: message.owner,
      agentId: message.agentId,
      action: message.action,
      paramsHash: message.paramsHash,
      nonce: message.nonce,
      issuedAt: message.issuedAt.toString(10),
      expiry: message.expiry.toString(10),
    },
    signature,
    params,
  };
}

type HttpResult = { readonly status: number; readonly body: Record<string, unknown> };

async function readBody(response: Response): Promise<HttpResult> {
  const text = await response.text();
  try {
    return { status: response.status, body: JSON.parse(text) as Record<string, unknown> };
  } catch {
    return { status: response.status, body: { raw: text } };
  }
}

async function perimeterGet(stack: Stack, path: string): Promise<HttpResult> {
  return readBody(
    await stack.app.request(path, {
      method: "GET",
      headers: { "x-exec-token": stack.execToken },
    }),
  );
}

async function ownerGet(stack: Stack, agentId: string, path: string): Promise<HttpResult> {
  const envelope = await signOwnerAction("read", agentId, {});
  const header = Buffer.from(JSON.stringify(envelope), "utf8").toString("base64url");
  return readBody(
    await stack.app.request(path, {
      method: "GET",
      headers: { "x-owner-action": header, "x-exec-token": stack.execToken },
    }),
  );
}

async function ownerPost(
  stack: Stack,
  path: string,
  envelope: SignedEnvelope,
): Promise<HttpResult> {
  return readBody(
    await stack.app.request(path, {
      method: "POST",
      headers: { "content-type": "application/json", "x-exec-token": stack.execToken },
      body: JSON.stringify(envelope),
    }),
  );
}

/* -------------------------------------------------------------------------- */
/* Settings helpers                                                           */
/* -------------------------------------------------------------------------- */

/** The wire shape `parseLendingSettingsParams` accepts. */
type SettingsParams = {
  triggerHf: string;
  targetHf: string;
  maxPerAction: { token: string | null; maxWei: string }[];
  minSecondsBetweenActions: number;
  rescueReserveCount: number;
  notifyOnlyBelowHf?: string;
};

function settingsToParams(settings: LendingSettings): SettingsParams {
  return {
    triggerHf: settings.triggerHf.toString(10),
    targetHf: settings.targetHf.toString(10),
    maxPerAction: settings.maxPerAction.map((cap) => ({
      token: cap.token,
      maxWei: cap.maxWei.toString(10),
    })),
    minSecondsBetweenActions: settings.minSecondsBetweenActions,
    rescueReserveCount: settings.rescueReserveCount,
    ...(settings.notifyOnlyBelowHf === undefined
      ? {}
      : { notifyOnlyBelowHf: settings.notifyOnlyBelowHf.toString(10) }),
  };
}

function upsertCap(
  params: SettingsParams,
  token: string | null,
  maxWei: bigint,
): void {
  const key = token === null ? null : token.toLowerCase();
  const existing = params.maxPerAction.find(
    (cap) => (cap.token === null ? null : cap.token.toLowerCase()) === key,
  );
  if (existing === undefined) {
    params.maxPerAction.push({ token, maxWei: maxWei.toString(10) });
    return;
  }
  existing.maxWei = maxWei.toString(10);
}

/**
 * Apply the flags an operator named onto a settings object, MERGE-STYLE.
 *
 * `lendingSettings` is a FULL REPLACEMENT on the wire, so a CLI that built its
 * payload from defaults would silently reset every field the operator did not
 * mention — the `live-lp settings` discipline, and the reason this merges over
 * the STORED row rather than over `DEFAULT_LENDING_SETTINGS`.
 */
function applySettingsFlags(
  base: SettingsParams,
  flags: Flags,
  usdt: Address,
): SettingsParams {
  const next: SettingsParams = {
    ...base,
    maxPerAction: base.maxPerAction.map((cap) => ({ ...cap })),
  };
  const trigger = mantissaFlag(flags, "trigger-hf");
  if (trigger !== undefined) next.triggerHf = trigger.toString(10);
  const target = mantissaFlag(flags, "target-hf");
  if (target !== undefined) next.targetHf = target.toString(10);
  const notify = mantissaFlag(flags, "notify-below-hf");
  if (notify !== undefined) next.notifyOnlyBelowHf = notify.toString(10);
  if (flags.get("clear-notify-below-hf") === "true") delete next.notifyOnlyBelowHf;
  const minSeconds = flags.get("min-seconds");
  if (minSeconds !== undefined && minSeconds !== "true") {
    next.minSecondsBetweenActions = intFlag(flags, "min-seconds", LENDING_MIN_SECONDS_BETWEEN_ACTIONS);
  }
  const rescues = flags.get("rescues");
  if (rescues !== undefined && rescues !== "true") {
    next.rescueReserveCount = intFlag(flags, "rescues", DEFAULT_LENDING_SETTINGS.rescueReserveCount);
  }
  const usdtCeiling = usdtFlag(flags, "max-repay-usdt");
  if (usdtCeiling !== undefined) upsertCap(next, usdt, usdtCeiling);
  const bnbCeiling = etherFlag(flags, "max-repay-bnb");
  if (bnbCeiling !== undefined) upsertCap(next, null, bnbCeiling);
  return next;
}

/* -------------------------------------------------------------------------- */
/* census                                                                     */
/* -------------------------------------------------------------------------- */

async function commandCensus(flags: Flags): Promise<void> {
  requireBoot("census");
  const { venue, venusVenue, rpcUrls, readers } = await readOnlyLending();
  const rpcOverride = flags.get("rpc-url");
  const url =
    rpcOverride !== undefined && rpcOverride !== "true" && rpcOverride.trim() !== ""
      ? rpcOverride.trim()
      : (rpcUrls[0] ?? READER_NETWORK.publicRpcUrl);
  const client = createPublicClient({ chain: READER_NETWORK.chain, transport: http(url) });
  const chainId = await client.getChainId();
  if (chainId !== 56) {
    throw new Error(`The configured RPC served chain ${chainId}, not 56. Nothing was probed.`);
  }
  const blockNumber = await client.getBlockNumber();

  const targets: readonly (readonly [Address, readonly string[]])[] = [
    [venue.vUsdt, LENDING_VUSDT_GRANTED_SELECTORS],
    [venue.vBnb, LENDING_VBNB_GRANTED_SELECTORS],
  ];
  const selectorsPresent = new Map<string, boolean>();
  for (const [target, signatures] of targets) {
    const code = (await client.getCode({ address: target })) ?? "0x";
    for (const signature of signatures) {
      const selector = toFunctionSelector(signature).slice(2).toLowerCase();
      selectorsPresent.set(
        `${target.toLowerCase()}:${signature}`,
        code.toLowerCase().includes(selector),
      );
    }
  }

  const usdtFromUnderlying = getAddress(
    await client.readContract({
      address: venue.vUsdt, abi: VTOKEN_UNDERLYING_ABI, functionName: "underlying",
    }),
  );
  const venusReaders = createVenusChainReaders({
    network: READER_NETWORK,
    rpcUrls: [url],
    venue: venusVenue,
    markets: [venue.vUsdt, venue.vBnb],
  });
  const routing = await venusReaders.readRoutingCensus([venue.vUsdt, venue.vBnb]);
  const pool = await readers.readSwapPool();

  const rows = censusRows({
    blockNumber,
    selectorsPresent,
    vUsdt: venue.vUsdt,
    vBnb: venue.vBnb,
    usdtFromUnderlying,
    usdtFromBoot: venue.usdt,
    routing,
    pool: { address: pool.pool, liquidity: pool.liquidity, token0: pool.token0 },
  });

  console.log(`live gate 1 — the lending census, re-probed at block ${blockNumber} on chain 56`);
  console.log(`rpc            : ${url}`);
  console.log(`vUSDT / vBNB   : ${venue.vUsdt} / ${venue.vBnb}`);
  console.log(`router / WBNB  : ${venue.routerV3} / ${venue.wbnb}`);
  console.log(`fee tier       : ${venue.swapFeeTier}`);
  console.log("");
  let failed = 0;
  for (const row of rows) {
    if (!row.pass) failed += 1;
    console.log(
      `[${row.pass ? "PASS" : "FAIL"}] ${row.name}\n`
        + `        expected ${row.expected}\n        observed ${row.observed}`,
    );
  }
  console.log("");
  console.log(
    `REFUSED SET (never granted by lendingSessionSpec; a template property, not a chain fact):\n  ${LENDING_REFUSED_SELECTORS.join(", ")}`,
  );
  console.log(`GRANTED SET: ${LENDING_GRANTED_SELECTORS.join(", ")}`);
  if ((process.env["VENUS_PRIME_ADDRESS"] ?? "").trim() === "") {
    console.warn(
      "\nWARNING: VENUS_PRIME_ADDRESS is unset, so the Prime implementation was read from the "
        + "Comptroller's own EIP-1967 slot and cannot match the recorded census. The lending "
        + "boot reads the SAME census and S1 asserts it, so a hire on this deployment will "
        + "refuse the grant. Set VENUS_PRIME_ADDRESS before live gate 2.",
    );
  }
  if (failed > 0) {
    console.error(
      `\n${failed} census row(s) FAILED. \`lendingSessionSpec\` asserts this census at S1, so a `
        + "grant on this deployment would be refused — re-take the census through the phase "
        + "process before hiring anything.",
    );
    process.exitCode = 1;
    return;
  }
  console.log("\nAll census rows PASS. Live gate 1 is satisfied for this block.");
}

/* -------------------------------------------------------------------------- */
/* guardable                                                                  */
/* -------------------------------------------------------------------------- */

async function commandGuardable(flags: Flags): Promise<void> {
  requireBoot("guardable");
  const account = needAddress(flags, "account");
  const { venue, readers, maxSagaSlippageBps } = await readOnlyLending();

  let reading;
  try {
    reading = await readers.readAccount(account, [venue.vUsdt, venue.vBnb]);
  } catch (error) {
    if (error instanceof LendingAccountTooComplexError) {
      console.log(
        `account ${account} is in more markets than this guard can price `
          + "(refusal `account-too-complex`); the guard is paused until it can.",
      );
      process.exitCode = 1;
      return;
    }
    throw error;
  }
  const view = venusBasisView(reading);
  const supported = (vToken: Address): boolean =>
    vToken.toLowerCase() === venue.vUsdt.toLowerCase()
    || vToken.toLowerCase() === venue.vBnb.toLowerCase();

  console.log(`guardable preview — account ${account}`);
  console.log(`block            : ${reading.blockNumber} (finalized)`);
  console.log(`protocolPaused   : ${reading.protocolPaused}`);
  console.log(
    `liquidation      : W ${view.pair.liquidationRisk.collateral} D ${view.pair.liquidationRisk.debt} `
      + `HF ${view.pair.liquidationRisk.healthFactor ?? "inf"} matched=${view.liquidationMatched}`,
  );
  console.log(
    `borrowing power  : W ${view.pair.borrowingPower.collateral} D ${view.pair.borrowingPower.debt} `
      + `HF ${view.pair.borrowingPower.healthFactor ?? "inf"} matched=${view.borrowingPowerMatched}`,
  );
  if (!view.liquidationMatched || !view.borrowingPowerMatched) {
    console.error(
      "PROTOCOL MISMATCH: the local reconstruction does not equal the protocol's own answer. "
        + "The guard FAILS CLOSED on this rather than acting on a smaller number.",
    );
  }
  let guardableDebt = false;
  console.log("markets:");
  for (const market of reading.markets) {
    const borrow = market.borrowCurrent ?? market.borrowStored;
    if (borrow === 0n && market.vTokenBalance === 0n && !market.collateralMember) continue;
    const isSupported = supported(market.vToken);
    if (borrow > 0n && isSupported) guardableDebt = true;
    console.log(
      `  ${market.vTokenSymbol.padEnd(8)} ${market.vToken} member=${market.collateralMember ? "y" : "n"} `
        + `borrow=${borrow} supported=${isSupported ? "yes" : "NO — this guard cannot repay it"} `
        + `repayPaused=${market.repayPaused}`,
    );
  }
  console.log(
    `guardable        : ${guardableDebt ? "yes" : "NO — no debt in a pinned market (vUSDT / vBNB)"}`,
  );

  const budgetWei = etherFlag(flags, "budget");
  if (budgetWei === undefined) {
    console.log(
      "\n(no --budget: the sizing half needs a budget, because `reserveCapFloorWei` is priced "
        + "on what the arm's swap would mint. Re-run with --budget <BNB> for the floors.)",
    );
    return;
  }
  const reserveBps = reserveBpsFlag(flags);
  const rescueReserveCount = intFlag(flags, "rescues", DEFAULT_LENDING_SETTINGS.rescueReserveCount);
  const reserveNativeWei = (budgetWei * BigInt(reserveBps)) / 10_000n;
  const supplyNativeWei = budgetWei - reserveNativeWei;
  const [supplyQuote, tierQuote] = await Promise.all([
    readers.quote({ tokenIn: venue.wbnb, tokenOut: venue.usdt, amountInWei: supplyNativeWei }),
    reserveNativeWei > 0n
      ? readers.quote({ tokenIn: venue.wbnb, tokenOut: venue.usdt, amountInWei: reserveNativeWei })
      : Promise.resolve(0n),
  ]);
  const floor = (quoted: bigint): bigint =>
    quoted <= 0n ? 0n : (quoted * BigInt(10_000 - maxSagaSlippageBps)) / 10_000n;
  const report = lendingPreviewReport({
    budgetWei,
    reserveBps,
    rescueReserveCount,
    mintUsdtWei: floor(supplyQuote),
    tierBuyBackUsdtWei: floor(tierQuote),
    capDayWei: null,
    reserveCapWei: null,
    usdt: venue.usdt,
    ttlSec: MAX_VENUS_SESSION_SECONDS,
  });
  console.log("\nsizing (priced at the floors — this is what a hire must clear):");
  for (const line of report) console.log(`  ${line}`);
  console.log(
    "\nNOTE: these floors are computed here from the SAME quoter the plane uses, but the "
      + "receipt that binds them to a hire comes from `GET /lending/guardable` in receipt mode, "
      + "which `provision` fetches for you.",
  );
}

/* -------------------------------------------------------------------------- */
/* preview                                                                    */
/* -------------------------------------------------------------------------- */

async function commandPreview(flags: Flags): Promise<void> {
  requireBoot("preview");
  const budgetWei = etherFlag(flags, "budget");
  if (budgetWei === undefined) throw new Error("--budget <BNB> is required.");
  const reserveBps = reserveBpsFlag(flags);
  const rescueReserveCount = intFlag(flags, "rescues", DEFAULT_LENDING_SETTINGS.rescueReserveCount);
  const ttlSec = intFlag(flags, "ttl-sec", MAX_VENUS_SESSION_SECONDS);

  const { venue, readers, maxSagaSlippageBps } = await readOnlyLending();
  const reserveNativeWei = (budgetWei * BigInt(reserveBps)) / 10_000n;
  const supplyNativeWei = budgetWei - reserveNativeWei;

  const floor = (quoted: bigint): bigint =>
    quoted <= 0n ? 0n : (quoted * BigInt(10_000 - maxSagaSlippageBps)) / 10_000n;
  const mintOverride = usdtFlag(flags, "mint-usdt");
  const tierOverride = usdtFlag(flags, "tier-buyback-usdt");
  const [supplyQuote, tierQuote] =
    mintOverride !== undefined && tierOverride !== undefined
      ? [0n, 0n]
      : await Promise.all([
          readers.quote({ tokenIn: venue.wbnb, tokenOut: venue.usdt, amountInWei: supplyNativeWei }),
          reserveNativeWei > 0n
            ? readers.quote({ tokenIn: venue.wbnb, tokenOut: venue.usdt, amountInWei: reserveNativeWei })
            : Promise.resolve(0n),
        ]);

  const report = lendingPreviewReport({
    budgetWei,
    reserveBps,
    rescueReserveCount,
    mintUsdtWei: mintOverride ?? floor(supplyQuote),
    tierBuyBackUsdtWei: tierOverride ?? floor(tierQuote),
    capDayWei: etherFlag(flags, "cap-day") ?? null,
    reserveCapWei: usdtFlag(flags, "reserve-cap") ?? null,
    usdt: venue.usdt,
    ttlSec,
  });
  console.log("lending hire sizing preview — READ ONLY, nothing was signed or sent");
  console.log(`usdt              : ${venue.usdt} (derived from vUSDT.underlying())`);
  console.log(`pool              : ${venue.swapPool} fee ${venue.swapFeeTier}`);
  for (const line of report) console.log(line);
}

/* -------------------------------------------------------------------------- */
/* provision — live gate 2                                                    */
/* -------------------------------------------------------------------------- */

async function commandProvision(flags: Flags): Promise<void> {
  requireBoot("provision");
  const agentId = need(flags, "agent-id");
  const account = needAddress(flags, "account");
  const budgetWei = etherFlag(flags, "budget");
  if (budgetWei === undefined) throw new Error("--budget <BNB> is required.");
  const reserveBps = reserveBpsFlag(flags);
  const rescueReserveCount = intFlag(flags, "rescues", DEFAULT_LENDING_SETTINGS.rescueReserveCount);
  const ttlSec = intFlag(flags, "ttl-sec", MAX_VENUS_SESSION_SECONDS);
  const maxRepayUsdt = usdtFlag(flags, "max-repay-usdt");
  if (maxRepayUsdt === undefined) {
    throw new Error(
      "--max-repay-usdt <USDT> is required: `maxPerAction` must name one ceiling per pinned "
        + "debt market, and an empty list is a guard with no amount it may pay.",
    );
  }
  const maxRepayBnb = etherFlag(flags, "max-repay-bnb");

  const stack = await buildStack({ withHire: true });
  try {
    const venue = stack.lending.venue;
    // `resolveOwnerWallet` is the `provision-venus-agent` posture: under
    // EIP-7702 the wallet IS the owner's own EOA, so this DERIVES an address
    // and spends nothing. `--wallet` skips even that read.
    const wallet = optionalAddress(flags, "wallet")
      ?? (await stack.provider.resolveOwnerWallet({
        owner: authorityFromPrivateKey(ownerKey()),
      })).address;

    const marketsRaw = flags.get("markets");
    const debtMarkets =
      marketsRaw === undefined || marketsRaw === "true"
        ? [venue.vUsdt]
        : marketsRaw.split(",").map((entry) => {
            const trimmed = entry.trim();
            if (!isAddress(trimmed, { strict: false })) {
              throw new Error(`--markets contains "${trimmed}", which is not an address.`);
            }
            return getAddress(trimmed);
          });
    const pinsVBnb = debtMarkets.some((market) => market.toLowerCase() === venue.vBnb.toLowerCase());
    if (pinsVBnb && maxRepayBnb === undefined) {
      throw new Error(
        "--max-repay-bnb <BNB> is required when --markets pins vBNB: `enforceLendingV1Profile` "
          + "refuses settings with no ceiling for a pinned market.",
      );
    }

    /* ---- 1. The receipt-mode preview. READ ONLY. ------------------------- */
    const query = new URLSearchParams({
      account,
      budgetWei: budgetWei.toString(10),
      reserveBps: String(reserveBps),
      maxPerActionUsdtWei: maxRepayUsdt.toString(10),
      rescueReserveCount: String(rescueReserveCount),
    });
    const preview = await perimeterGet(stack, `/lending/guardable?${query.toString()}`);
    if (preview.status !== 200) {
      show("preview REFUSED", preview);
      process.exitCode = 1;
      return;
    }
    const previewData = preview.body["data"] as Record<string, unknown> | undefined;
    const receipt = previewData?.["previewReceipt"];
    const sizing = previewData?.["sizing"] as Record<string, unknown> | undefined;
    show("preview", previewData);
    if (typeof receipt !== "string") {
      console.error(
        "\nThe preview returned NO receipt. `LENDING_PREVIEW_SECRET` is unset, and S1 is "
          + "FAIL-CLOSED on that (R3.8): the hire would refuse `preview-receipt-unavailable`. "
          + "Set the secret and re-run. Nothing was sent.",
      );
      process.exitCode = 1;
      return;
    }
    if (previewData?.["guardable"] !== true) {
      console.error(
        "\nThe account is NOT guardable (no debt in a pinned market, or the read refused). "
          + "Refusing to hire a guard with nothing to do. Nothing was sent.",
      );
      process.exitCode = 1;
      return;
    }

    const capDayWei = etherFlag(flags, "cap-day")
      ?? BigInt(String(sizing?.["minimumCapDayWei"] ?? "0"));
    const reserveCapWei = usdtFlag(flags, "reserve-cap")
      ?? BigInt(String(sizing?.["reserveCapFloorWei"] ?? "0"));
    if (capDayWei <= 0n || reserveCapWei <= 0n) {
      throw new Error(
        "The preview returned no cap floors and none were named. Pass --cap-day <BNB> and "
          + "--reserve-cap <USDT> explicitly, or fix the preview.",
      );
    }

    const report = lendingPreviewReport({
      budgetWei,
      reserveBps,
      rescueReserveCount,
      mintUsdtWei: BigInt(String(sizing?.["mintUsdtWei"] ?? "0")),
      tierBuyBackUsdtWei: 0n,
      capDayWei,
      reserveCapWei,
      usdt: venue.usdt,
      ttlSec,
    });
    console.log("\nWHAT THIS HIRE WOULD GRANT:");
    for (const line of report) console.log(`  ${line}`);

    /* ---- 2. The funding requirement, computed not quoted ----------------- */
    //
    // The SAME reader and the SAME headroom the S1 route uses — the one the
    // stack composed. A second spelling here would be a second number to keep
    // honest, and this is the number an operator funds wallet B against.
    const evidence = stack.hireEvidence;
    const headroomWei = stack.grantGasHeadroomWei;
    if (evidence === undefined || headroomWei === undefined) {
      throw new Error("The hire deps were not composed; `provision` cannot read the funding half.");
    }
    const funding = await evidence.readFunding(
      wallet, headroomWei, Math.floor(Date.now() / 1000),
    );
    show("funding requirement (wallet B)", funding);

    const balanceBefore = await stack.provider.getBalance({ address: wallet });
    console.log(`\nwallet B          : ${wallet}`);
    console.log(`balance before    : ${formatEther(balanceBefore)} BNB`);
    console.log(`debt markets      : ${debtMarkets.join(", ")}`);
    console.log(`session TTL       : ${ttlSec}s`);

    requireYesLive(
      "provision",
      flags,
      `consume an owner nonce, generate a session key inside the plane, and GRANT an on-chain `
        + `session on ${wallet} with native cap ${formatEther(capDayWei)} BNB/day and USDT cap `
        + `${formatUnits(reserveCapWei, 18)}/day for ${ttlSec}s. The grant itself costs the `
        + `KeyStore registration fee plus gas, paid by wallet B.`,
    );

    /* ---- 3. S1 ----------------------------------------------------------- */
    const settingsParams: SettingsParams = {
      triggerHf: (mantissaFlag(flags, "trigger-hf") ?? DEFAULT_LENDING_SETTINGS.triggerHf).toString(10),
      targetHf: (mantissaFlag(flags, "target-hf") ?? DEFAULT_LENDING_SETTINGS.targetHf).toString(10),
      maxPerAction: [
        ...(debtMarkets.some((m) => m.toLowerCase() === venue.vUsdt.toLowerCase())
          ? [{ token: venue.usdt as string, maxWei: maxRepayUsdt.toString(10) }]
          : []),
        ...(pinsVBnb && maxRepayBnb !== undefined
          ? [{ token: null, maxWei: maxRepayBnb.toString(10) }]
          : []),
      ],
      minSecondsBetweenActions: intFlag(flags, "min-seconds", LENDING_MIN_SECONDS_BETWEEN_ACTIONS),
      rescueReserveCount,
      ...(mantissaFlag(flags, "notify-below-hf") === undefined
        ? {}
        : { notifyOnlyBelowHf: (mantissaFlag(flags, "notify-below-hf") ?? 0n).toString(10) }),
    };
    const parsedSettings = parseLendingSettingsParams(settingsParams);
    if (!parsedSettings.ok) {
      throw new Error(`The settings this run would sign are invalid: ${parsedSettings.message}`);
    }

    const hireParams = {
      walletAddress: wallet,
      token: venue.usdt,
      capDayWei: capDayWei.toString(10),
      openNativeBudgetWei: budgetWei.toString(10),
      ttlSec,
      sizingPreset: "lending-v1",
      guardedAccount: account,
      debtMarkets,
      reserveCapWei: reserveCapWei.toString(10),
      reserveBps,
      settings: settingsParams,
      previewReceipt: receipt,
    };
    const envelope = await signOwnerAction("provisionAgent", agentId, hireParams);
    const s1 = await ownerPost(stack, `/agents/${agentId}/session`, envelope);
    show("S1 (POST /agents/:id/session)", s1);
    if (s1.status !== 200) {
      console.error("\nS1 refused. Nothing was granted. The session key, if any, was not used.");
      process.exitCode = 1;
      return;
    }

    /* ---- 4. The grant ---------------------------------------------------- */
    const agent = await stack.agentStore.getAgentById(agentId);
    const pending = agent?.pendingGrant ?? null;
    if (agent === null || pending === null) {
      console.error(
        "\nThe row carries no pending grant, so there is nothing to grant. Read the S1 body above.",
      );
      process.exitCode = 1;
      return;
    }
    const sessionKey = await stack.agentStore.getAgentSessionKey(agent.ownerAddress, agent.id);
    if (sessionKey === null) {
      console.error(
        "\nThe sealed session key could not be read back (EXECUTION_MASTER_KEY?). The grant is "
          + "NOT attempted: granting a key this process cannot later use would strand the hire.",
      );
      process.exitCode = 1;
      return;
    }
    console.log(
      `\ngranting — this signs with the OWNER key and costs gas. session ${pending.sessionAddress}, `
        + `${pending.permissions.calls.length} call rule(s), expiry ${new Date(pending.expiresAt * 1000).toISOString()}`,
    );
    const ownerAuthority = authorityFromPrivateKey(ownerKey());
    const ownerWallet = await stack.provider.resolveOwnerWallet({ owner: ownerAuthority });
    const granted = await stack.provider.grantSession({
      wallet: ownerWallet,
      owner: ownerAuthority,
      spec: pending.sessionSpec,
      agent: authorityFromPrivateKey(sessionKey),
    });
    const balanceAfter = await stack.provider.getBalance({ address: wallet });
    console.log(`granted           : publicKey ${granted.publicKey}`);
    console.log(`balance after     : ${formatEther(balanceAfter)} BNB`);
    console.log(
      `MEASURED GRANT COST: ${formatEther(balanceBefore - balanceAfter)} BNB `
        + `(record this in FINDINGS (bn) — live gate 2)`,
    );

    /* ---- 5. Convergence -------------------------------------------------- */
    const converged = await ownerGet(stack, agentId, `/agents/${agentId}/session`);
    show("convergence (GET /agents/:id/session)", converged);
    console.log(
      "\nA row still reading `provisioning` with `missing: [...]` is NOT a failure yet — the "
        + "convergence is caller-independent and the 60 s sweep re-runs it. `permissions-differ` "
        + "IS terminal: the relay's enumeration did not match the persisted set byte-for-byte.",
    );
  } finally {
    await stack.close();
  }
}

/* -------------------------------------------------------------------------- */
/* arm — live gate 3                                                          */
/* -------------------------------------------------------------------------- */

async function commandArm(flags: Flags): Promise<void> {
  requireBoot("arm");
  const agentId = need(flags, "agent-id");
  const stack = await buildStack({ withHire: false });
  try {
    const ownerAddress = privateKeyToAccount(ownerKey()).address;
    const agent = await stack.agentStore.getAgent(ownerAddress, agentId);
    if (agent === null) throw new Error(`No agent ${agentId} for owner ${ownerAddress}.`);
    const guard = await stack.lending.guards.get(agent.ownerAddress, agent.id);
    if (guard === null) {
      throw new Error(
        "This agent has no lending guard row yet; the hire's convergence writes it. Run "
          + "`live-lending status --agent-id <id>` (which converges) and try again.",
      );
    }
    const stored = await stack.lending.settingsStore.get(agent.ownerAddress, agent.id);
    if (stored === null) {
      throw new Error(
        "No `lending_settings` row. The arm is a CONTINUATION of the settings the owner signed "
          + "at S1 and never a second admission (AUDIT P19), so there is nothing to arm with.",
      );
    }
    const budgetWei = BigInt(agent.sessionFacts?.hireSizing?.openNativeBudgetWei ?? "0");
    const reserveNativeWei = (budgetWei * BigInt(guard.reserveBps)) / 10_000n;

    console.log(`agent             : ${agent.id} owner ${agent.ownerAddress}`);
    console.log(`wallet B          : ${agent.walletAddress}`);
    console.log(`guarded account A : ${guard.guardedAccount}`);
    console.log(`guard status      : ${guard.status}${guard.hold === null ? "" : ` hold=${guard.hold}`}`);
    console.log(`debt markets      : ${guard.debtMarkets.join(", ")}`);
    console.log(
      `budget            : ${formatEther(budgetWei)} BNB ⇒ BNB tier ${formatEther(reserveNativeWei)} `
        + `/ supply leg ${formatEther(budgetWei - reserveNativeWei)} BNB`,
    );
    console.log(`settings digest   : ${stored.digest}`);
    const balanceBefore = await stack.provider.getBalance({ address: agent.walletAddress });
    console.log(`balance before    : ${formatEther(balanceBefore)} BNB`);

    requireYesLive(
      "arm",
      flags,
      `submit ONE batch under the standing session that swaps ${formatEther(budgetWei - reserveNativeWei)} `
        + `BNB to USDT and mints vUSDT, leaving ${formatEther(reserveNativeWei)} BNB as the gas tier. `
        + "The arm's msg.value meters against the native day cap.",
    );

    const envelope = await signOwnerAction("lendingArm", agentId, {
      settings: stored.params,
      budgetWei: budgetWei.toString(10),
      reserveBps: guard.reserveBps,
    });
    const response = await ownerPost(stack, `/agents/${agentId}/lending/arm`, envelope);
    show("arm", response);
    const balanceAfter = await stack.provider.getBalance({ address: agent.walletAddress });
    console.log(`\nbalance after     : ${formatEther(balanceAfter)} BNB`);
    console.log(`delta             : ${formatEther(balanceBefore - balanceAfter)} BNB`);
    if (response.status !== 200) process.exitCode = 1;
  } finally {
    await stack.close();
  }
}

/* -------------------------------------------------------------------------- */
/* status                                                                     */
/* -------------------------------------------------------------------------- */

async function commandStatus(flags: Flags): Promise<void> {
  requireBoot("status");
  const agentId = flags.get("agent-id");
  const stack = await buildStack({ withHire: false });
  try {
    const ownerAddress = privateKeyToAccount(ownerKey()).address;
    const guards = (await stack.lending.guards.listForWorker()).filter(
      (row) => agentId === undefined || agentId === "true" || row.agentId === agentId,
    );
    if (guards.length === 0) {
      console.log("(no lending guard rows for this database)");
      return;
    }
    for (const guard of guards) {
      await printGuardStatus(stack, guard, ownerAddress);
    }
  } finally {
    await stack.close();
  }
}

async function printGuardStatus(
  stack: Stack,
  guard: LendingGuardRecord,
  ownerAddress: Address,
): Promise<void> {
  console.log(`\n=== agent ${guard.agentId} owner ${guard.ownerAddress} ===`);
  console.log(`status            : ${guard.status}${guard.hold === null ? "" : ` hold=${guard.hold}`}`);
  console.log(`guarded account A : ${guard.guardedAccount}`);
  console.log(`debt markets      : ${guard.debtMarkets.join(", ")}`);
  console.log(`budget / split    : ${formatEther(guard.budgetWei)} BNB @ ${guard.reserveBps} bps`);
  console.log(`reserve cap       : ${formatUnits(guard.reserveCapWei, 18)} USDT/day`);
  console.log(
    `arm               : tx ${guard.armTxHash ?? "-"} block ${guard.armBlock ?? "-"} `
      + `mint ${formatUnits(guard.mintUsdtWei, 18)} USDT`,
  );
  console.log(
    `claim             : seq ${guard.actionSeq} last `
      + `${guard.lastActionAtMs === null ? "-" : new Date(guard.lastActionAtMs).toISOString()}`,
  );

  const agent = await stack.agentStore.getAgent(guard.ownerAddress, guard.agentId);
  if (agent === null) {
    console.log("agent row         : ABSENT (the guard row outlived its agent)");
    return;
  }
  console.log(
    `session           : status ${agent.status} expiry `
      + `${agent.sessionFacts === null ? "-" : new Date(agent.sessionFacts.expiry * 1000).toISOString()}`,
  );

  // The RECORDED view — zero chain reads, and it says how stale it is.
  if (guard.ownerAddress.toLowerCase() === ownerAddress.toLowerCase()) {
    const view = await ownerGet(stack, guard.agentId, `/agents/${guard.agentId}/lending/view`);
    show("owner view (RECORDED by the worker — never a live read)", view.body["data"] ?? view.body);
  } else {
    console.log(
      "owner view        : skipped — the owner key in this environment does not own this row.",
    );
  }

  // The LIVE reads, labelled as such. The view above is what the worker wrote;
  // these two are what the chain says now, and the difference IS the staleness.
  const settings = await stack.lending.settingsStore.get(guard.ownerAddress, guard.agentId);
  const parsed = settings === null ? null : parseLendingSettingsParams(settings.params);
  const rescueReserveCount =
    parsed !== null && parsed.ok
      ? parsed.value.rescueReserveCount
      : DEFAULT_LENDING_SETTINGS.rescueReserveCount;
  try {
    const reserve = await stack.lending.readers.readReserve(agent.walletAddress);
    const tier = lendingTier({
      nativeBalanceWei: reserve.nativeBalance,
      rescueReserveCount,
      rescuesChargedInWindow: 0,
      outstandingArmNativeWei: 0n,
    });
    const capacity = lendingCapacity({
      reading: reserve,
      tier,
      slippageBps: stack.lending.maxSagaSlippageBps,
      tierToUsdtWei: 0n,
      usdtToNativeWei: 0n,
    });
    const retirePlan = planLendingRetire(reserve);
    console.log("\nreserve (LIVE, wallet B, one pinned finalized block):");
    console.log(`  block           : ${reserve.blockNumber}`);
    console.log(`  idle USDT       : ${formatUnits(reserve.usdtBalance, 18)}`);
    console.log(`  supplied USDT   : ${formatUnits(capacity.suppliedUsdtWei, 18)} (at exchangeRateStored)`);
    console.log(`  vUSDT balance   : ${reserve.vUsdtBalance}`);
    console.log(`  pool cash       : ${formatUnits(reserve.cash, 18)} USDT`
      + `${capacity.poolCashLow ? "   ⚠ below the supply — a full redeem cannot clear in one go" : ""}`);
    console.log(`  BNB tier        : ${formatEther(tier.tierBnbWei)} (floor ${formatEther(tier.floorWei)}, `
      + `${tier.reservedSubmissions} submission(s) reserved)`);
    console.log(`  allowances      : vUSDT ${reserve.usdtAllowanceToVUsdt} router ${reserve.usdtAllowanceToRouter}`);
    console.log(
      `  retire plan     : redeem ${formatUnits(retirePlan.redeemAmountWei, 18)} / swap-in `
        + `${formatUnits(retirePlan.swapInWei, 18)} USDT`
        + `${retirePlan.poolShort ? `   POOL-SHORT: ${formatUnits(retirePlan.remainderUsdtWei, 18)} would stay on Venus` : ""}`,
    );
  } catch (error) {
    console.warn(
      `\nreserve (LIVE)    : UNREADABLE — ${sanitizeMessage(error instanceof Error ? error.message : "unknown")}`,
    );
  }

  try {
    const reading = await stack.lending.readers.readAccount(
      guard.guardedAccount, guard.debtMarkets,
    );
    const view = venusBasisView(reading);
    console.log("\naccount A (LIVE):");
    console.log(`  block           : ${reading.blockNumber} (finalized)`);
    console.log(
      `  liquidation HF  : ${view.pair.liquidationRisk.healthFactor ?? "inf"} matched=${view.liquidationMatched}`,
    );
    console.log(
      `  borrowing HF    : ${view.pair.borrowingPower.healthFactor ?? "inf"} matched=${view.borrowingPowerMatched}`,
    );
    for (const market of reading.markets) {
      const borrow = market.borrowCurrent ?? market.borrowStored;
      if (borrow === 0n) continue;
      console.log(`  borrow          : ${market.vTokenSymbol} ${borrow} repayPaused=${market.repayPaused}`);
    }
  } catch (error) {
    console.warn(
      `\naccount A (LIVE)  : UNREADABLE — ${sanitizeMessage(error instanceof Error ? error.message : "unknown")}`,
    );
  }
}

/* -------------------------------------------------------------------------- */
/* settings                                                                   */
/* -------------------------------------------------------------------------- */

async function commandSettings(flags: Flags): Promise<void> {
  requireBoot("settings");
  const agentId = need(flags, "agent-id");
  const stack = await buildStack({ withHire: false });
  try {
    const ownerAddress = privateKeyToAccount(ownerKey()).address;
    const agent = await stack.agentStore.getAgent(ownerAddress, agentId);
    if (agent === null) throw new Error(`No agent ${agentId} for owner ${ownerAddress}.`);
    const stored = await stack.lending.settingsStore.get(agent.ownerAddress, agent.id);
    const current = stored === null ? null : parseLendingSettingsParams(stored.params);
    const base: SettingsParams =
      current !== null && current.ok
        ? settingsToParams(current.value)
        : settingsToParams(DEFAULT_LENDING_SETTINGS);
    if (stored === null) {
      console.warn(
        "NOTE: no stored settings row; merging over DEFAULTS. Every field you do not name will "
          + "be a default, because `lendingSettings` is a FULL REPLACEMENT on the wire.",
      );
    }
    const next = applySettingsFlags(base, flags, stack.lending.venue.usdt);
    const parsed = parseLendingSettingsParams(next);
    if (!parsed.ok) throw new Error(`The merged settings are invalid: ${parsed.message}`);

    show("current (stored)", base);
    show("next (merged over the stored row)", next);
    console.log(`\ndigest now        : ${stored?.digest ?? "(none)"}`);
    console.log(`digest next       : ${lendingSettingsDigest(next)}`);

    requireYesLive(
      "settings",
      flags,
      "sign and store new lending settings. No gas is spent, but the worker recomputes this "
        + "digest every cycle and acts on it with the owner's money — thresholds, the rescue "
        + "ceiling and the cooldown all change what a live rescue will do.",
    );

    const envelope = await signOwnerAction("lendingSettings", agentId, next);
    const response = await ownerPost(stack, `/agents/${agentId}/lending/settings`, envelope);
    show("settings", response);
    if (response.status !== 200) process.exitCode = 1;
  } finally {
    await stack.close();
  }
}

/* -------------------------------------------------------------------------- */
/* retire — live gate 7                                                       */
/* -------------------------------------------------------------------------- */

async function commandRetire(flags: Flags): Promise<void> {
  requireBoot("retire");
  const agentId = need(flags, "agent-id");
  const acceptPartial = flags.get("accept-partial") === "true";
  const stack = await buildStack({ withHire: false });
  try {
    const ownerAddress = privateKeyToAccount(ownerKey()).address;
    const agent = await stack.agentStore.getAgent(ownerAddress, agentId);
    if (agent === null) throw new Error(`No agent ${agentId} for owner ${ownerAddress}.`);
    const guard = await stack.lending.guards.get(agent.ownerAddress, agent.id);
    if (guard === null) throw new Error("This agent has no lending guard row.");

    const reserve = await stack.lending.readers.readReserve(agent.walletAddress);
    const plan = planLendingRetire(reserve);
    console.log(`agent             : ${agent.id} status ${guard.status}`
      + `${guard.hold === null ? "" : ` hold=${guard.hold}`}`);
    console.log(`wallet B          : ${agent.walletAddress}`);
    console.log(`idle USDT         : ${formatUnits(reserve.usdtBalance, 18)}`);
    console.log(`supplied USDT     : ${formatUnits(plan.suppliedUsdtWei, 18)}`);
    console.log(`redeem            : ${formatUnits(plan.redeemAmountWei, 18)} USDT`);
    console.log(`swap in           : ${formatUnits(plan.swapInWei, 18)} USDT ⇒ BNB`);
    console.log(
      `pool short        : ${plan.poolShort ? `YES — ${formatUnits(plan.remainderUsdtWei, 18)} USDT would stay on Venus` : "no"}`,
    );
    console.log(`accept-partial    : ${acceptPartial}`);
    if (plan.poolShort && !acceptPartial) {
      console.warn(
        "\nThe route will REFUSE `pool-cash-short` without --accept-partial. That refusal is the "
          + "correct answer: leaving part of the reserve on Venus is a DECLARED CHOICE, not "
          + "something a route makes silently.",
      );
    }

    requireYesLive(
      "retire",
      flags,
      `submit ONE batch that redeems ${formatUnits(plan.redeemAmountWei, 18)} USDT from vUSDT, `
        + `swaps ${formatUnits(plan.swapInWei, 18)} USDT to WBNB and unwraps it back to wallet B. `
        + "The USDT approve meters at its approved amount against the rolling day cap.",
    );

    const envelope = await signOwnerAction(
      "lendingRetire", agentId, acceptPartial ? { acceptPartial: true } : {},
    );
    const response = await ownerPost(stack, `/agents/${agentId}/lending/retire`, envelope);
    show("retire", response);

    // HTTP 200 IS NOT "RETIRED". The outcome block is the authority, and this is
    // the one place an operator is most likely to read a 200 as success.
    const data = response.body["data"] as Record<string, unknown> | undefined;
    const outcome = data?.["retire"] as Record<string, unknown> | undefined;
    const guardView = data?.["guard"] as Record<string, unknown> | undefined;
    console.log("\n--- READ THIS, NOT THE STATUS CODE -------------------------------");
    console.log(`HTTP              : ${response.status}`);
    console.log(`submission status : ${String(outcome?.["status"] ?? "-")} code=${String(outcome?.["code"] ?? "-")}`);
    console.log(`txHash            : ${String(outcome?.["txHash"] ?? "-")}`);
    console.log(`cleared           : ${String(outcome?.["cleared"] ?? "-")}`);
    console.log(`residue on Venus  : ${String(outcome?.["residueUsdtWei"] ?? "-")} USDT wei`);
    console.log(`guard status now  : ${String(guardView?.["status"] ?? "-")} hold=${String(guardView?.["hold"] ?? "-")}`);
    console.log(
      "A 200 means the route ran. `cleared: true` AND guard status `retired` is what means the "
        + "reserve came back; `held` + `retire-unknown` means the outcome is ambiguous and v1 "
        + "ships NO lending UNKNOWN resolver — the reserve stays recoverable with the passkey.",
    );
    if (response.status !== 200) process.exitCode = 1;
  } finally {
    await stack.close();
  }
}

/* -------------------------------------------------------------------------- */
/* worker                                                                     */
/* -------------------------------------------------------------------------- */

/**
 * Narrow the worker's queue to ONE agent without touching the store.
 *
 * `runLendingWorkerOnce` has no per-agent filter — its queue IS
 * `listForWorker()` — so the alternative to this proxy is a cycle that also
 * drives every OTHER armed guard on the same database, which is not what an
 * operator running a single gate asked for. The proxy can only NARROW: every
 * other method is forwarded to the real store with the real receiver, so the
 * fence, the claim CAS and the cooldown are the store's own.
 */
function scopeGuardsToAgent(store: LendingGuardStore, agentId: string): LendingGuardStore {
  return new Proxy(store, {
    get(target, property): unknown {
      if (property === "listForWorker") {
        return async (): Promise<readonly LendingGuardRecord[]> =>
          (await target.listForWorker()).filter((row) => row.agentId === agentId);
      }
      const value: unknown = Reflect.get(target, property, target);
      return typeof value === "function"
        ? (value as (...args: readonly unknown[]) => unknown).bind(target)
        : value;
    },
  });
}

function logOutcome(outcome: LendingWorkerAgentOutcome): void {
  const parts = [
    `agent=${outcome.agentId}`,
    `action=${outcome.action}`,
    ...(outcome.condition === undefined ? [] : [`condition=${outcome.condition}`]),
    ...(outcome.market === undefined ? [] : [`market=${outcome.market}`]),
    ...(outcome.amountWei === undefined ? [] : [`amount=${outcome.amountWei}`]),
    ...(outcome.healthFactor === undefined ? [] : [`hf=${outcome.healthFactor ?? "inf"}`]),
    ...(outcome.consecutive === undefined ? [] : [`consecutive=${outcome.consecutive}`]),
    ...(outcome.effect === undefined ? [] : [`effect=${outcome.effect}`]),
  ];
  console.log(`[live-lending] ${parts.join(" ")} reason=${sanitizeMessage(outcome.reason)}`);
}

async function commandWorker(flags: Flags): Promise<void> {
  requireBoot("worker");
  if (flags.get("once") !== "true") {
    throw new Error(
      "`worker` runs exactly one cycle and takes --once explicitly. The daemon is "
        + "`npm run lending-worker`; this subcommand is for driving ONE gate.",
    );
  }
  const live = commandIsLive("worker", flags);
  const agentId = flags.get("agent-id");
  const stack = await buildStack({ withHire: false });
  try {
    const guards =
      agentId === undefined || agentId === "true"
        ? stack.lending.guards
        : scopeGuardsToAgent(stack.lending.guards, agentId);
    const queue = await guards.listForWorker();
    console.log(`queue             : ${queue.length} guard row(s)`);
    for (const row of queue) {
      console.log(
        `  ${row.agentId} status=${row.status}${row.hold === null ? "" : ` hold=${row.hold}`} `
          + `A=${row.guardedAccount}`,
      );
    }
    if (live) {
      requireYesLive(
        "worker",
        flags,
        `drive ONE LIVE cycle over ${queue.length} guard row(s). A dispatched rescue submits `
          + "`repayBorrowBehalf` under the standing session and spends the owner's reserve.",
      );
    } else {
      console.log(
        "\nREHEARSAL (the default): every branch reports what a live cycle WOULD record and "
          + "writes NOTHING — no observation, no claim, no action row, no snapshot, no journal "
          + "row and no submission. Chain reads still happen; they ARE the decision.",
      );
    }

    const deps: LendingWorkerDeps = {
      agentStore: stack.agentStore,
      journal: stack.journal,
      killswitch: stack.killswitch,
      provider: stack.provider,
      guards,
      settingsStore: stack.lending.settingsStore,
      observations: stack.lending.observations,
      readers: stack.lending.readers,
      venue: stack.lending.venue,
      intervalMs: stack.lending.intervalMs,
      maxObservationAgeMs: stack.lending.maxObservationAgeMs,
      agentConcurrency: stack.lending.agentConcurrency,
      maxSagaSlippageBps: stack.lending.maxSagaSlippageBps,
      now: Date.now,
      dryRun: !live,
      log: logOutcome,
      ...(live
        ? {
            reconcile: async (): Promise<void> => {
              await reconcile({
                provider: stack.provider,
                journal: stack.journal,
                resolveWallet: async (owner, id) => {
                  const agent = await stack.agentStore.getAgentById(id);
                  if (agent === null) return null;
                  if (agent.ownerAddress !== (owner as Address).toLowerCase()) return null;
                  return {
                    address: agent.walletAddress,
                    chainId: NETWORK.chainId,
                    ownerAddress: agent.ownerAddress,
                    custodyModel: agent.custodyModel,
                  };
                },
              });
            },
          }
        : {}),
    };
    const report = await runLendingWorkerOnce(deps);
    console.log(
      `\n[live-lending] cycle done outcomes=${report.outcomes.length} `
        + `reconciled=${report.reconciled} dry-run=${report.dryRun}`,
    );
    console.log(
      "ONE `--once` run against a freshly armed guard CANNOT fire: one cycle cannot produce two "
        + "observations, and the spacing is enforced against the RECORDED stamp, so two runs "
        + "against one lagging node cannot manufacture a confirmation.",
    );
  } finally {
    await stack.close();
  }
}

/* -------------------------------------------------------------------------- */
/* Entry                                                                      */
/* -------------------------------------------------------------------------- */

export const USAGE = `
live-lending — the Venus guard-on-behalf operator CLI (MARKETPLACE-LENDING-AGENT §12).

  npm run live-lending -- census
  npm run live-lending -- guardable --account 0xA [--budget 0.05] [--reserve-pct 20] [--rescues 6]
  npm run live-lending -- preview   --account 0xA --budget 0.05 [--reserve-pct 20]
                                    [--rescues 6] [--cap-day 0.5] [--reserve-cap 200] [--ttl-sec 604800]
  npm run live-lending -- provision --agent-id guard-1 --account 0xA --budget 0.05
                                    --max-repay-usdt 50 [--markets 0xvUSDT[,0xvBNB]] [--max-repay-bnb 0.02]
                                    [--cap-day 0.5] [--reserve-cap 200] [--reserve-pct 20]
                                    [--trigger-hf 1.20] [--target-hf 1.50] [--min-seconds 300] --yes-live
  npm run live-lending -- arm       --agent-id guard-1 --yes-live
  npm run live-lending -- status    [--agent-id guard-1]
  npm run live-lending -- settings  --agent-id guard-1 [--trigger-hf 1.25] [--max-repay-usdt 60] --yes-live
  npm run live-lending -- retire    --agent-id guard-1 [--accept-partial] --yes-live
  npm run live-lending -- worker    --once [--agent-id guard-1] [--yes-live]

Every spending path refuses without --yes-live and prints what it would spend.
\`worker\` rehearses by DEFAULT; only --yes-live makes a cycle live.
`;

async function main(): Promise<void> {
  const [subcommand, ...rest] = process.argv.slice(2);
  if (subcommand === undefined || subcommand === "help" || subcommand === "--help") {
    console.log(USAGE);
    if (subcommand !== undefined && subcommand !== "help" && subcommand !== "--help") {
      process.exitCode = 1;
    }
    return;
  }
  if (!(LENDING_CLI_COMMANDS as readonly string[]).includes(subcommand)) {
    console.log(USAGE);
    console.error(`\nUnknown subcommand "${subcommand}".`);
    process.exitCode = 1;
    return;
  }
  const command = subcommand as LendingCliCommand;
  const flags = parseFlags(rest);
  // FIRST, before anything is constructed: a misspelled flag on this CLI is one
  // keystroke from spending.
  assertKnownFlags(command, flags);

  switch (command) {
    case "census":
      await commandCensus(flags);
      return;
    case "guardable":
      await commandGuardable(flags);
      return;
    case "preview":
      await commandPreview(flags);
      return;
    case "provision":
      await commandProvision(flags);
      return;
    case "arm":
      await commandArm(flags);
      return;
    case "status":
      await commandStatus(flags);
      return;
    case "settings":
      await commandSettings(flags);
      return;
    case "retire":
      await commandRetire(flags);
      return;
    case "worker":
      await commandWorker(flags);
      return;
    default:
      return;
  }
}

const entryPath = process.argv[1];
if (entryPath !== undefined && import.meta.url === pathToFileURL(resolve(entryPath)).href) {
  main().catch((error: unknown) => {
    const message = error instanceof Error ? error.message : String(error);
    if (message !== YES_LIVE_SENTINEL) {
      console.error(`\nlive-lending failed: ${message}`);
      process.exitCode = 1;
    }
  });
}
