/** AWS SDK/provider environment members that may redirect identity, endpoints or client policy. */
export const BILLING_FORBIDDEN_AWS_ENV_NAMES = Object.freeze([
  "AWS_ACCESS_KEY_ID",
  "AWS_SECRET_ACCESS_KEY",
  "AWS_SESSION_TOKEN",
  "AWS_SECURITY_TOKEN",
  "AWS_PROFILE",
  "AWS_DEFAULT_PROFILE",
  "AWS_SHARED_CREDENTIALS_FILE",
  "AWS_CONFIG_FILE",
  "AWS_SDK_LOAD_CONFIG",
  "AWS_CREDENTIAL_PROCESS",
  "credential_process",
  "AWS_WEB_IDENTITY_TOKEN_FILE",
  "AWS_ROLE_ARN",
  "AWS_ROLE_SESSION_NAME",
  "AWS_CONTAINER_CREDENTIALS_FULL_URI",
  "AWS_CONTAINER_AUTHORIZATION_TOKEN",
  "AWS_CONTAINER_AUTHORIZATION_TOKEN_FILE",
  "AWS_SSO_SESSION",
  "AWS_CA_BUNDLE",
  "AWS_ENDPOINT_URL",
  "AWS_ENDPOINT_URL_STS",
  "AWS_ENDPOINT_URL_KMS",
  "AWS_ENDPOINT_URL_SECRETS_MANAGER",
  "AWS_IGNORE_CONFIGURED_ENDPOINT_URLS",
  "AWS_USE_FIPS_ENDPOINT",
  "AWS_USE_DUALSTACK_ENDPOINT",
  "AWS_REGION",
  "AWS_DEFAULT_REGION",
  "AWS_STS_REGIONAL_ENDPOINTS",
  "AWS_MAX_ATTEMPTS",
  "AWS_RETRY_MODE",
  "AWS_EC2_METADATA_DISABLED",
  "AWS_METADATA_SERVICE_TIMEOUT",
  "AWS_METADATA_SERVICE_NUM_ATTEMPTS",
] as const);

export function hasForbiddenBillingAwsEnvironment(environment: NodeJS.ProcessEnv): boolean {
  return BILLING_FORBIDDEN_AWS_ENV_NAMES.some((name) =>
    Object.prototype.hasOwnProperty.call(environment, name));
}
